### PR TITLE
Changes to get ready for invoking engine's setup() method from main()

### PR DESCRIPTION
**Pull request by mulkieran**
The purpose of this PR is to prepare to be calling setup() functions from main().

Mostly this PR is about tidying up our error handling, removing unused error constructors, and so forth.
It also rearranges main so that it can return an exit code in the recommended fashion. It rearranges some other methods in stratis.rs for a similar purpose. It moves some files at the top-level to ~~runner~~ stratis subdirectory for better encapsulation and to more readily access the engine::EngineError type.

### CODE REVIEW

**Comment by agrover** [comment]
so far looks great.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Superceded by #341.

**Pull request closed without merging**
