### PR TITLE
Add valgrind tests to CI

### LINKED ISSUE #3230: Add valgrind task to CI
We know that we can run valgrind on stratisd and have detected at least one memory leak, now fixed. Can we run it in our nightly CI?

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #3230

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran I'm wondering whether we want to further up the timeout values for the purposes of valgrind. The current timeout values in #3255 work outside of valgrind but valgrind seems to slow it down enough that we may need even longer timeouts. What are your thoughts?

**Comment by mulkieran** [comment]
@jbaublitz I don't see any problem w/ longer timeouts.

**Comment by jbaublitz** [comment]
@mulkieran Yeah unfortunately the timeouts don't occur each time I'm going to run it a few more times through rebases before I consider it truly not a problem.

**Review by mulkieran — CHANGES_REQUESTED** [review]
This all looks good except that development rust toolchain version needs to move up to 1.68.0.

At present, the valgrind report does emit some things that look like errors, but none of the tasks fail.

Can the tasks fail? If they can only report but not fail, running them nightly rather than on every PR would probably be enough.

**Comment by jbaublitz** [comment]
They can't fail based on valgrind errors so nightly might be best.

**Comment by mulkieran** [comment]
> They can't fail based on valgrind errors so nightly might be best.

Ok! Let's swap it over to nightly once the PR is ready.

**Comment by jbaublitz** [comment]
I think this is ready.

**Review by bmr-cymru — APPROVED** [review]

**Pull request merged**
