### PR TITLE
Add the standard license header for rust files.

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@trgill  review?

This is just a convenience, for when I might be adding new files to the repo.

**Comment by agrover** [comment]
Yeah I dunno if we need this, can you just cut n paste from an existing file?

**Comment by mulkieran** [comment]
It is not a risky change, though.

**Comment by agrover** [comment]
well no, I just don't see why we need it. We already have the LICENSE file, and it includes the text of this comment, see Exhibit A at the bottom

**Comment by mulkieran** [comment]
There is no point in discussing this further.

**Pull request closed without merging**
