### PR TITLE
Instantiate D-Bus objects when engine is set up

### LINKED ISSUE #497: DBus objects should be created on daemon load
If I run the daemon, create a pool, exit/restart the system, then run stratisd again, it appears that the pool is recreated properly (DM targets etc) but `stratis pool list` doesn't show anything.

### LINKED ISSUE #503: We should use Rc::clone() where that's what we mean
It is recommended and prevents confusion with the other clones.

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves #497.
Resolves #503.

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover Feel free to take a look. I'm still trying to figure out how to make an automatic test.

**Comment by mulkieran** [comment]
Well, there were no panics when running the D-Bus tests, which is a good sign. The problem with testing is that this tests things via the D-Bus which are absolutely not part of the sim engine. So, one thing to consider is whether to extend the sim engine somehow so that when it is initialized it has an existing pool, for instance.

**Comment by agrover** [comment]
Looks good to me, yup.

**Comment by agrover** [comment]
This passes my test:
1. run stratisd
1. create pool
1. `pool list` shows created pool
1. kill stratisd
1. unmount /dev/stratis/.mdv-(uuid)
1. dmsetup remove_all
1. run stratisd
1. `pool list` shows existing pool

Good. What doesn't work for the moment is skipping the kill/unmount/remove_all steps, due to https://github.com/stratis-storage/devicemapper-rs/issues/120.

**Comment by mulkieran** [comment]
What happens instead?

**Comment by agrover** [comment]
```
syscall 'open' failed, Device or resource busy
Note: you cannot run this tool with these options on live metadata.
thin_repair failed, pool unusable
```

**Comment by mulkieran** [comment]
@agrover @trgill up for final review.

**Comment by agrover** [comment]
👍

**Comment by agrover** [comment]
rebased to resolve merge conflicts.

**Comment by agrover** [comment]
testing revealed some spots needing fixing from the merge, rebased.

**Comment by agrover** [comment]
going to go ahead and merge this so I can tag 0.1 today.

**Pull request merged**
