### PR TITLE
Issue project 192

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #2211
Related to stratis-storage/project#192

### CODE REVIEW

**Comment by jbaublitz** [comment]
TODO: test adding block devices to pools bound to Tang.

**Comment by jbaublitz** [comment]
@mulkieran Putting up for initial review. I've verified:
1. Clevis bind and unbind work as expected.
2. Adding a block device to a pool bound to a tang server works as expected.
3. Unlocking a pool with `unlock_method == "clevis"` works even when a key is not set in the kernel keyring.

@drckeefe I'm requesting your review just in case you want to test anything from the command line.

**Comment by mulkieran** [comment]
Pushing this back to in progress, as some significant changes were proposed for the D-Bus API in standup yesterday.

**Comment by mulkieran** [comment]
@jbaublitz Please rebase

**Comment by jbaublitz** [comment]
@bgurney-rh CI failed here because stratisd was already running on Jenkins.

**Comment by bgurney-rh** [comment]
I checked the test node that stratisd-nonrust was running on, and whatever stale stratisd process was there at the time is not there now.  I restarted the test.

**Comment by bgurney-rh** [comment]
It failed again; same failure, different node.

But be careful, that "daemon already running" error is from a test that specifically tests for that scenario:
```
python3 -m unittest --verbose tests.misc.test_startup.TestUniqueInstance.test_unique_instance
test_unique_instance (tests.misc.test_startup.TestUniqueInstance)
Verify that a second stratisd instance can not be started. ... Stderr from this invocation of stratisd:
Error: Daemon already running with supposed pid: 425183

ok

----------------------------------------------------------------------
Ran 1 test in 0.017s
```

This is the real failure in that last test run:
```
python3 -m unittest --verbose tests.udev.test_udev
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib64/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/usr/lib64/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/fedora/workspace/stratisd-nonrust/tests/client-dbus/tests/udev/test_udev.py", line 26, in <module>
    from stratisd_client_dbus import (
  File "/home/fedora/workspace/stratisd-nonrust/tests/client-dbus/src/stratisd_client_dbus/__init__.py", line 19, in <module>
    from ._implementation import (
  File "/home/fedora/workspace/stratisd-nonrust/tests/client-dbus/src/stratisd_client_dbus/_implementation.py", line 27, in <module>
    _POOL_SPEC = ET.fromstring(SPECS["org.storage.stratis2.pool.r1"])
KeyError: 'org.storage.stratis2.pool.r1'
make: *** [Makefile:24: udev-tests] Error 1
```

**Comment by mulkieran** [comment]
New commits in #2291 should fix the failure.

**Comment by mulkieran** [comment]
@jbaublitz Please take a look at requested changes in https://github.com/stratis-storage/stratisd/pull/2291. I haven't looked very closely at crypt.rs, devices.rs, or keys.rs changes, but will do more work on the CLI side first, most likely.

**Pull request closed without merging**
