### PR TITLE
Add script to get Stratis info from devicemapper path

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/650

### CODE REVIEW

**Comment by mulkieran** [comment]
Either the tests aren't running or the script is working correctly

**Comment by mulkieran** [comment]
Fixed a spelling error in the test script...

**Comment by mulkieran** [comment]
no failures...

**Review by bmr-cymru — APPROVED** [review]
Tested with the PR branch, this is all working well for me:

```
# new_tool /dev/mapper/stratis-1-4a0b9aa45f454e2fbef3516739281386-thin-fs-7614e4fa083941d7bde6c96d3aefe841 --output symlink
/dev/stratis/p1/fs1-snap
# new_tool /dev/mapper/stratis-1-4a0b9aa45f454e2fbef3516739281386-thin-fs-7614e4fa083941d7bde6c96d3aefe841 --output pool-name
p1
# new_tool /dev/mapper/stratis-1-4a0b9aa45f454e2fbef3516739281386-thin-fs-7614e4fa083941d7bde6c96d3aefe841 --output filesystem-name
fs1-snap
```

**Comment by mulkieran** [comment]
Previous failure was due to a bug in the tests...

**Comment by mulkieran** [comment]
Re-running with enhanced tests...

**Comment by mulkieran** [comment]
Expect Packit builds to fail.

**Comment by mulkieran** [comment]
https://github.com/stratis-storage/testing/pull/239 should go in shortly after this is merged.

**Comment by mulkieran** [comment]
@jbaublitz Note that there is a new pylint task in githooks

**Review by jbaublitz — APPROVED** [review]

**Pull request merged**
