### PR TITLE
Add a simple 'help' target to the Makefile

### PR DESCRIPTION
**Pull request by bmr-cymru**
Add a simple 'help' target to the Makefile that uses '##' comments to
signify help text for a make target or command:

e.g.:

```
  ## Build rust documentation
  docs-rust:
          cargo doc --no-deps
```

Produces output like the following for "make help":

```
$ make help

Usage:
  make <target>

Targets:
  outdated                       Run cargo outdated
  license                        Run cargo license
  bloat                          Run cargo bloat
  audit                          Run cargo audit
  expand                         Run cargo expand
  fmt                            Run cargo fmt
  fmt-macros                     Run cargo fmt for stratisd_proc_macros
  fmt-travis                     Run cargo fmt for CI jobs
  fmt-macros-travis              Run cargo fmt on stratisd_proc_macros for CI jobs
  fmt-shell                      Check shell formatting with shfmt
  fmt-shell-ci                   Check shell formatting with shfmt for CI
  build                          Build stratisd
  build-tests                    Build the stratisd test suite
  build-extras                   Build stratisd extra binaries
  build-min                      Build stratisd-min and stratis-min for early userspace
  stratis-dumpmetadata           Build the stratis-dumpmetadata program
  stratis-min                    Build stratis-min for early userspace
  stratisd-min                   Build stratisd-min for early userspace
  install-cfg                    Install stratisd configuration
  install                        Install stratisd binaries and configuration
  build-and-install              Build and install stratisd binaries and configuration
  clean-cfg                      remove installed configuration files
  clean-ancillary                remove installed non-primary tools generated by the build process
  clean-primary                  remove installed command-line tools and daemons generated by the build process
  clean                          remove installed items
  test-loop                      Tests with loop devices
  test-real                      Tests with real devices
  test                           Basic tests
  test-clevis-real               Clevis tests with real devices
  test-clevis-real-should-fail   Clevis real device tests that are expected to fail
  test-clevis-loop               Clevis tests with loop devices
  test-clevis-loop-should-fail   Clevis loop device tests that are expected to fail
  yamllint                       Run yamllint on workflow files
  docs-travis                    Build docs-rust for CI
  docs-rust                      Build rust documentation
  clippy-macros                  Run clippy on stratisd_proc_macros
  clippy                         Run clippy on the current source tree
  help                           Show help
```

### CODE REVIEW

**Comment by mulkieran** [comment]
@bmr-cymru Is this ready or still a bit in progress ?

**Comment by bmr-cymru** [comment]
Yes! The CI failure was a udev error on Ubuntu - I think the PR is ready for review now.

**Comment by bmr-cymru** [comment]
Rebased

**Review by mulkieran — APPROVED** [review]

**Review by bgurney-rh — APPROVED** [review]

**Comment by drckeefe** [comment]
bmr-cymru  would it be possible to add capital Rs to the start of the clean target descriptions, the words "remove"

**Comment by bmr-cymru** [comment]
> bmr-cymru would it be possible to add capital Rs to the start of the clean target descriptions, the words "remove"

Good catch, thanks! I've fixed those up now.

**Review by drckeefe — APPROVED** [review]

**Pull request merged**
