### PR TITLE
Update Clevis thumbprint generation for SHA-1 to SHA-256

### LINKED ISSUE #2670: Investigation and updates around Clevis change from SHA-1 to SHA-256
Clevis has changed their hashing algorithm for thumbprints.

1. Investigate whether Tang responds to SHA-1 hashes in the newest version in addition to SHA-256.
2. Update stratisd to generate SHA-256 hashes for the thumbprint from the advertisement moving forward.
3. Test that this update works when binding to Tang specifically.

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2670

### CODE REVIEW

**Comment by jbaublitz** [comment]
I've pushed this PR because the `checks_with_tang` CI tests should give us a good indication of whether this will cause the current version of Fedora to fail.

**Comment by jbaublitz** [comment]
It appears that the tests for Tang pass which is great! I'll update the pinned version in `Cargo.toml`.

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
@jbaublitz Ok! Please rebase.

**Comment by jbaublitz** [comment]
@mulkieran Rebased.

**Comment by jbaublitz** [comment]
@mulkieran Rebased. Does this look like it's ready to go? Do you want me to squash the commits given how trivial the change is?

**Comment by mulkieran** [comment]
> @mulkieran Rebased. Does this look like it's ready to go? Do you want me to squash the commits given how trivial the change is?

@jbaublitz Ok! Feel free to sqash in place and force push.

**Comment by jbaublitz** [comment]
Rebased.

**Pull request merged**
