### PR TITLE
Move most of devlinks functionality into a udev rule

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes stratis-storage/project#95

@mulkieran One important note is that I left the devlinks module around for two specific cases:
* Testing
* Triggering synthetic uevents when filesystems and pools are renamed to indicate to udev that it should make the symlinks consistent

Other than that, I've deleted a good deal of the code in devlinks and moved it into the udev rule and the script it calls.

### CODE REVIEW

**Comment by jbaublitz** [comment]
We'll see how CI fares with these changes.

**Comment by jbaublitz** [comment]
@mulkieran All of the tests should pass except for the udev test with duplicate pool names. That one should pass once we get the udev rule on the Jenkins nodes but until then will not.

**Comment by jbaublitz** [comment]
I am very confused as to why that test passed...

**Comment by jbaublitz** [comment]
Ok, the logs indicate that the tests passing is valid. stratisd fails to rename the symlinks as expected, but it's simply that the tests don't depend on the symlink, only that udev picks up the pools being renamed.

**Comment by mulkieran** [comment]
This might also close #1987.

**Comment by mulkieran** [comment]
@jbaublitz Please rebase.

**Pull request closed without merging**
