### PR TITLE
Fix a bug and introduce an improvement around ensuring only single instance of stratisd is running

### LINKED ISSUE #893: stratisd should not require setting up pid file when called with CLI options that exit immediately
See #853 for an example of the problem.

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves #893.
Resolves: #895.

### CODE REVIEW

**Comment by mulkieran** [comment]
Waiting for clippy update...

**Comment by mulkieran** [comment]
Still waiting for clippy update...

**Comment by agrover** [comment]
I don't understand why 6e2ee98 is needed, why doesn't the existing code work as intended?

**Comment by mulkieran** [comment]
I got the idea from the flock man page:

> Locks created by flock() are associated with an open file table entry. This means that duplicate file descriptors (created by, for example, fork(2) or dup(2)) refer to the same lock, and this lock may be modified or released using any of these descriptors. Furthermore, the lock is released either by an explicit LOCK_UN operation on any of these duplicate descriptors, or when all such descriptors have been closed.

**Comment by agrover** [comment]
please see #897, I think only a smaller change is all that's required.

I've tested #897 as working for me (i.e. duplicate daemons do not start) with rustc 1.25.0 on F27.

**Comment by mulkieran** [comment]
After one and a half days or thereabouts, building clippy from master branch for CI seems like not a bad idea.

**Comment by agrover** [comment]
let's work on this over in #897. closing.

**Pull request closed without merging**
