### PR TITLE
Unify rollback to restore backed up LUKS2 headers and refresh Clevis state after binding

### LINKED ISSUE #2776: Stratisd runs clevis-encrypt-tang (indirectly), which might try to access /dev/tty, which fails
I just got this:

```
# stratis pool add-data pool0 /dev/sdc1
Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: Error: Command failed: cmd: "/usr/bin/clevis" "luks" "bind" "-d" "/dev/sdc1" "-k" "/run/stratisd/keyfiles/TnnfKGM2pPSdQARk/FzS522IYoo" "-t" "2" "tang" "{\"url\":\"http://192.168.100.1\"}", exit reason: 1 stdout:  stderr: Warning: Value 512 is outside of the allowed entropy range, adjusting it.
The advertisement contains the following signing keys:

pvzqrQJhzQifxDID5q-82PLMddzalSmMCwmW-9jQHtU
/usr/bin/clevis-encrypt-tang: line 120: /dev/tty: No such device or address
Invalid input!
Usage: jose jwe fmt -i JWE [-I CT] [-o JWE] [-O CT] [-c]

Converts a JWE between serialization formats

  -i JSON --input=JSON     Parse JWE from JSON
  -i FILE --input=FILE     Read JWE from FILE
  -i -    --input=-        Read JWE from standard input

  -I FILE --detached=FILE  Read decoded ciphertext from FILE
  -I -    --detached=-     Read decoded ciphertext from standard input

  -o JSON --output=JSON    Parse JWE from JSON
  -o FILE --output=FILE    Read JWE from FILE
  -o -    --output=-       Read JWE from standard input
                           Default: "-"

  -O JSON --detach=JSON    Parse JWE from JSON
  -O FILE --detach=FILE    Read JWE from FILE
  -O -    --detach=-       Read JWE from standard input

  -c      --compact        Output JWE using compact serialization

Failed to import token from file.
Error saving metadata to LUKS2 header in device /dev/sdc1
Unable to update metadata; operation cancelled
Error adding new binding to /dev/sdc1
. 
```

This is for a encrypted pool with a "tang" binding but no "keyring" binding.  I think I made the tang binding like so:

```
# stratis pool bind tang pool0 http://192.168.100.1 --trust-url
```

Line 120 of clevis-encrypt-tang is this:

```
        echo "The advertisement contains the following signing keys:" >&2
        echo >&2
        jose jwk thp -i- -a "${CLEVIS_DEFAULT_THP_ALG}" <<< "$ver" >&2
        echo >&2
        read -r -p "Do you wish to trust these keys? [ynYN] " ans < /dev/tty
        [[ "$ans" =~ ^[yY]$ ]] || exit 1
```

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2776

### CODE REVIEW

**Comment by mulkieran** [comment]
I think the tests error is a strange udev error...```udevadm settle``` failed.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks good! Please rebase and I'll merge. The tests that I wrote don't need to be put in this PR; we can consider it complete as is.

**Comment by jbaublitz** [comment]
@mulkieran Okay, this is ready!

**Comment by mulkieran** [comment]
Taking executive action and merging. It looks like GitHub workflows just wasn't able to get the test part of fedora:34 python-based-tests started at all.

**Pull request merged**
