### PR TITLE
tests: make client-dbus udev tests verbose

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
At the time, I was afraid that I'd effectively need to add "--verbose -rsx", but didn't know if I could add multiple-word options in the PYTEST_OPTS

Let me try it and see what happens.

**Comment by bgurney-rh** [comment]
Looks like it works; here's the end of the output from the (new) stratisd-nonrust test:
```
tests/udev/test_udev.py::UdevAdd::test_combinations PASSED               [ 16%]
tests/udev/test_udev.py::UdevAdd::test_duplicate_pool_name PASSED        [ 33%]
tests/udev/test_udev.py::UdevAdd::test_existing PASSED                   [ 50%]
tests/udev/test_udev.py::UdevAdd::test_simple_udev_add PASSED            [ 66%]
tests/udev/test_udev.py::UdevAdd::test_simultaneous PASSED               [ 83%]
tests/udev/test_udev.py::UdevAdd::test_spurious_adds PASSED              [100%]
```

**Comment by mulkieran** [comment]
> Looks like it works; here's the end of the output from the (new) stratisd-nonrust test:
> 
> ```
> tests/udev/test_udev.py::UdevAdd::test_combinations PASSED               [ 16%]
> tests/udev/test_udev.py::UdevAdd::test_duplicate_pool_name PASSED        [ 33%]
> tests/udev/test_udev.py::UdevAdd::test_existing PASSED                   [ 50%]
> tests/udev/test_udev.py::UdevAdd::test_simple_udev_add PASSED            [ 66%]
> tests/udev/test_udev.py::UdevAdd::test_simultaneous PASSED               [ 83%]
> tests/udev/test_udev.py::UdevAdd::test_spurious_adds PASSED              [100%]
> ```

Good, let's go w/ that.

**Comment by bgurney-rh** [comment]
Ah yes; I was so concerned with there being only one commit, that I forgot the description of what changed became stale.  I've updated the commit message.

**Comment by mulkieran** [comment]
If so moved we should do the same for stratis-cli tests, whitebox and blackbox perhaps. I'll file an issue.

**Pull request merged**
