### PR TITLE
Future-proof Python code

### PR DESCRIPTION
**Pull request by jbaublitz**
~~As long as CI passes with these changes, we should merge this to avoid problems when we upgrade to Fedora 31 on Jenkins machines.~~

Related: https://github.com/stratis-storage/project/issues/175.

### CODE REVIEW

**Comment by mulkieran** [comment]
What are the problems?

**Comment by jbaublitz** [comment]
We discussed in stand up that this is related to later versions of pylint and isort in Fedora 31.

**Comment by mulkieran** [comment]
Given the conflicts in the equivalent stratis CLI PR, we'll have to do a little planning.

**Comment by mulkieran** [comment]
> As long as CI passes with these changes, we should merge this to avoid problems when we upgrade to Fedora 31 on Jenkins machines.

We wouldn't expect to have problems on the Jenkins machines, but we do have to manage our Travis CI. If we wanted to merge this now, under the expectation that we'll move up to Fedora 31, we could, but we should also add a set of Travis tasks, matching the ones for the recommended development interpreter, but with the default versions of things from Fedora 31. Then when we have all succesfully moved up, we'ld make those the recommended development interpreter tasks and drop the old recommended development interpreter tasks.

**Comment by jbaublitz** [comment]
Conflicts resolved and .travis.yml is updated.

**Pull request closed without merging**
