### PR TITLE
strat_engine: Change name length error message from chars to bytes

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
Here's a simple command to reproduce the test:
```
# stratis pool create spool3_プールですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですです /dev/nvme0n1p3
Execution failed:
stratisd failed to perform the operation that you requested. It returned the following information via the D-Bus: ERROR: Name has more than 255 characters : spool3_プールですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですですです.
```

**Comment by mulkieran** [comment]
Python lint failure because of new pylint version. #1635 will fix the problem.

**Comment by mulkieran** [comment]
#1635 is merged. Please rebase, and all tests should pass.

**Comment by bgurney-rh** [comment]
rebased.

**Pull request merged**
