### PR TITLE
Master devicemapper 0.15.0 next

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
rebases all around.

**Comment by mulkieran** [comment]
rebases all around.

**Comment by mulkieran** [comment]
rebased. Also, testing stratisd-client-dbus tests on Jenkins.

**Comment by mulkieran** [comment]
rebased and brought in necessary changes.

**Comment by mulkieran** [comment]
@agrover @trgill, final review please?

**Comment by agrover** [comment]
👍 MALR

**Pull request merged**
