### PR TITLE
Generate UML-diagram like graphs for particular modules in stratis

### PR DESCRIPTION
**Pull request by mulkieran**
These are somewhat useful for code visualization and this approach
seems to be the best available so far.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
This doesn't get run automatically. The major question is whether all are comfortable with the output location, which is easily changed.

**Comment by mulkieran** [comment]
I'ld like to use the walkdir crate, to see if I can just generate graphs for every module rather than have an ad-hoc list. This shouldn't be too hard.

**Comment by agrover** [comment]
:+1: if new file goes in scripts/, as we just did over in devicemapper.

**Comment by mulkieran** [comment]
I think this is identical to devicemapper version now.

**Pull request merged**
