### PR TITLE
Update crc to version 2.0.0

### PR DESCRIPTION
**Pull request by remilauzier**

### CODE REVIEW

**Comment by mulkieran** [comment]
ok to test

**Comment by mulkieran** [comment]
@remilauzier Thanks for the patch. I've placed it in the "Pending" slot, because we have a policy not to move up to a version that is higher than that currently in a version of Fedora that we expect to release to. But once that changes we'll be happy to go ahead with review, etc. The important CI failure is here: https://github.com/stratis-storage/stratisd/pull/2705/checks?check_run_id=3051605495.

**Comment by remilauzier** [comment]
Ok. I have made a pr on pagure for that, but a lot of things must fall in place before it can go forward.
https://src.fedoraproject.org/rpms/rust-crc/pull-request/1

**Comment by mulkieran** [comment]
@remilauzier Ok! Thanks for explaining.

**Comment by mulkieran** [comment]
Waiting on progress in Fedora, moving to August.

**Comment by decathorpe** [comment]
BTW: Feel free to update your dependencies even if they're not available in Fedora yet ... otherwise we'll end up playing a game of dependency chicken - the Rust stack is usually only updated for new major versions of crates "on demand", and if there's no demand for a new major version, we just don't do it (we sadly don't have infinite manpower).

**Comment by mulkieran** [comment]
Closing. We can always reopen if the Fedora packaging picks up again.

**Comment by mulkieran** [comment]
@remilauzier it seems like crc v2 is making its way into Fedora. Do you want to re-open this pull request or open a new one? We'll have to hold it until it lands in Fedora 34, but that should be very soon. I can't just reopen this PR, because the repo is gone.

**Comment by mulkieran** [comment]
@remilauzier Actually, there is no technical problem. I realized I could pick the commit from the PR and put it up again, see https://github.com/stratis-storage/stratisd/pull/2885, so there is nothing left for you to do.

**Pull request closed without merging**
