### PR TITLE
Do not store device size in BDA

### PR DESCRIPTION
**Pull request by mulkieran**
Use the RangeAllocator limit field as our source of this information.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill: Do we need to store the size of the device in the Static Header at all? This PR demonstrates that we don't actually do much with it. In #343, I've discovered that it is almost an inconvenience. When we initialize a BlockDev, it has a RangeAllocator which has a limit value, which is the size of the device. When we reconstruct the BlockDev during setup, we must get the RangeAllocator, and must at that time, find out the actual size of the device (which may differ from that on the BDA). When we instantiate the RangeAllocator, we are then in a position where the bda we have loaded is wrong about the size, the RangeAllocator is correct, and the value of the size actually on the BDA on the device is incorrect. We can update the value of the BDA in the BlockDev, but to get it correct on the device, we actually have to write it. We have a lot of ability for this to go wrong, so, the question is, do we actually need it at all?

**Comment by mulkieran** [comment]
@agrover @trgill review? I believe this could be ready to go. It leaves a chunk of unused space that is 12 bytes long, from the 20th to the 32nd byte. The alternative is to shift some data up, but it's not obvious to me that that would be useful.

**Comment by agrover** [comment]
> We can update the value of the BDA in the BlockDev, but to get it correct on the device, we actually have to write it. 

This field is not the "actual size of the blockdev", it's the "size of the blockdev that we expect to be able to use". If the two values differ, then that doesn't mean we need to correct the copy in the BDA, but rather that -- especially if the actual space is less than what we expect -- an assumption we were relying on has been violated and we probably need to fail ASAP so the admin can fix things. (We just had our data truncated, the sooner the admin knows, the more likely they can restore it intact.)

**Comment by mulkieran** [comment]
We already have a value for the size of the blockdev that we expect to be able to use, it's the largest sector yet allocated and we are keeping track of that via the data that is used to instantiate the blockdev mgr.

What is the problem if the device is smaller but no data is lost? Is that really an indication of anything bad? What precisely is the assumption that has been violated?

**Comment by trgill** [comment]
should we remove the "review final" tag on this PR?

**Comment by mulkieran** [comment]
Yes.

**Comment by agrover** [comment]
Storing the size seems very common. Therefore I think we should feel ok with keeping it in the BDA. See below:

LVM
64 bit size (I think in sectors)
in both MDA_header and raw_locn struct
source: lvm2 git lib/format_text/layout.h

ZFS
Name: “asize”
Value: DATA_TYPE_UINT64
Description: Amount of space that can be allocated from this top
level vdev
source: ZFS on-disk format PDF

XFS (xfs_rfsblock_t  sb_dblocks)
64bit count of blocks (blocks are usually 4K)
source: http://xfs.org/docs/xfsdocs-xml-dev/XFS_Filesystem_Structure/tmp/en-US/html/Allocation_Groups.html#Superblocks

ext4 (s_blocks_count_lo, s_blocks_count_hi)
64bit count of blocks (blocks are usually 4K)
source: https://ext4.wiki.kernel.org/index.php/Ext4_Disk_Layout

**Comment by mulkieran** [comment]
I'ld like to know why they do this...

**Comment by mulkieran** [comment]
Opened issue #435, instead.

**Pull request closed without merging**
