### PR TITLE
Annotate current development Rust toolchain

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/ci#191

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
Might as well pick up the one at line 475.

**Review by mulkieran — APPROVED** [review]

**Review by mulkieran — CHANGES_REQUESTED** [review]
Found just one more in nightly.yml, line 182.

**Comment by bgurney-rh** [comment]
I also found another one on nightly.yml, line 119; hopefully that's everything.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Ok. Squash the last two commits, or squash them all, and this is good to go.

**Comment by bgurney-rh** [comment]
Rebased.

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
