### PR TITLE
Adjustments for devicemapper PR #740

### PR DESCRIPTION
**Pull request by mulkieran**
Not to be committed.

### CODE REVIEW

**Comment by mulkieran** [comment]
Ignore errors.

**Comment by mulkieran** [comment]
@jbaublitz These are the only changes needed. You can approve if unsurprised.

**Review by jbaublitz — CHANGES_REQUESTED** [review]
There's actually one more change that I highlighted in stand up that we need. `ThinPoolDev::new()` now initializes with new parameters so we will need a `thinpooldev.error_on_queue()` after any call to `ThinPoolDev::new()`.

**Comment by mulkieran** [comment]
> There's actually one more change that I highlighted in stand up that we need. `ThinPoolDev::new()` now initializes with new parameters so we will need a `thinpooldev.error_on_queue()` after any call to `ThinPoolDev::new()`.

Aaah, yes. This should fix that.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
rebased, resolved conflicts, expect errors in CI tests.

**Comment by mulkieran** [comment]
Update once more to point at devicemapper branch that contains the "bug fix"

**Comment by mulkieran** [comment]
ignore errors.

**Comment by mulkieran** [comment]
Test that require devicemapper to work are going to fail...

**Comment by mulkieran** [comment]
obsolete

**Pull request closed without merging**
