### PR TITLE
Initial work for removing redundancy option

### LINKED ISSUE #2969: Remove redundancy option from PoolCreate method
it does nothing.

### PR DESCRIPTION
**Pull request by mulkieran**
Closes #2969

### CODE REVIEW

**Comment by mulkieran** [comment]
This will compete w/ other work currently happening w/ CreatePool, so I'm putting it in Pending and not completing it now.

**Comment by faangbait** [comment]
> This will compete w/ other work currently happening w/ CreatePool, so I'm putting it in Pending and not completing it now.

Can you specify/link to what functionality this will compete with? Is redundancy coming in from another direction in the near future?

**Comment by jbaublitz** [comment]
Hi @faangbait! I just want to chime in here to say that this would simply remove the redundancy operation which is effectively dead at the moment. The only option that it currently accepts is "none". While we eventually plan to add redundancy, our current recommendation is to use a RAID device underneath Stratis and provide that to the create pool method if redundancy is desired. This is not removing redundancy as a feature, just a placeholder parameter.

**Comment by mulkieran** [comment]
This might be completely out-of-date now.

**Pull request closed without merging**
