### PR TITLE
Bug fix for liminal device code

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Review by mulkieran — COMMENTED** [review]
This looks correct to me, but I'm worried that it might have a bad consequence, due to the issue discussed here: https://github.com/stratis-storage/stratisd/issues/3353 . The consequence would be that there is a pool that is setup but has no mounted filesystems. But the LUKS metadata gets corrupted. The pool cannot be started and all the devices are torn down and now the pool is basically impossible to set up in the normal way and may be entirely unrecoverable. That may very well be better than the alternatives, but I'ld like to introduce the possibility for your consideration.

**Comment by jbaublitz** [comment]
I think there are arguments on both ends. If we do tear down the pool, we could permanently lose data. If we don't, we could leave the devices in an unlocked state unintentionally which could leave sensitive data available to an attacker. I think data loss may be more of a concern here and I'm happy to simply default to putting the partially constructed pool into the partially constructed pool slot to be torn down through `stratis pool stop` later given that we now have the ability to do that through stratisd. What are your thoughts?

**Comment by mulkieran** [comment]
> I think there are arguments on both ends. If we do tear down the pool, we could permanently lose data. If we don't, we could leave the devices in an unlocked state unintentionally which could leave sensitive data available to an attacker. I think data loss may be more of a concern here and I'm happy to simply default to putting the partially constructed pool into the partially constructed pool slot to be torn down through `stratis pool stop` later given that we now have the ability to do that through stratisd. What are your thoughts?

That seems like the best choice that we have available.

**Comment by jbaublitz** [comment]
I think this is actually a real bug. I need to fix the tests.

**Comment by jbaublitz** [comment]
Blocked by #3385

**Comment by jbaublitz** [comment]
Merged in #3389

**Pull request closed without merging**
