### PR TITLE
Preliminary work on encryption

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #1807

### CODE REVIEW

**Comment by mulkieran** [comment]
Please take a look at https://github.com/stratis-storage/stratisd/pull/1818. I had a few in a previous review PR, but they mostly had to do with whether we should make encryption and the cache mutually exclusive, and we may change our minds about that.

**Comment by jbaublitz** [comment]
I've taken a look and have no problems with the changes.

**Comment by mulkieran** [comment]
@jbaublitz: I've added two more to #1818. These last two just make encryption and cache mutually exclusive as decided. If you're happy with all changes, please squash on to this PR.

**Comment by mulkieran** [comment]
@jbaublitz: If that all goes well, I'ld like you to pull out the parts of the PR that make encryption status available on the D-Bus into a separate PR, called henceforward "the encrypted property PR". I think that the parts to pull out of this PR in the dbus_api module are in the following files:

* src/dbus_api/consts.rs
* src/dbus_api/pool/mod.rs
* src/dbus_api/pool/pool_2_0/props.rs
* src/dbus_api/pool/pool_2_1/api.rs
* src/dbus_api/pool/pool_2_1/mod.rs
* src/dbus_api/pool/pool_2_1/props.rs
* src/dbus_api/pool/shared.rs

but they should be easy to sort out.

Outside the dbus_api module, you can just keep the declaration of ```is_encrypted``` in the ```Pool``` trait, and implement it in both ```StratPool``` and ```SimPool``` to just return ```false```.  You should also include ```tests/client-dbus/tests/dbus/pool/test_properties.py``` in the encrypted property PR.

We should be able to merge the encrypted property PR in a day or so, since it should contain nothing that isn't reasonably straightforward.

**Comment by jbaublitz** [comment]
Which one are we merging first?

**Comment by mulkieran** [comment]
> Which one are we merging first?

The "encrypted property PR".

**Comment by jbaublitz** [comment]
Rebased.

**Comment by jbaublitz** [comment]
The PR is up for review #1823

**Comment by jbaublitz** [comment]
Changes from #1818 applied.

**Comment by jbaublitz** [comment]
Rebased.

**Comment by jbaublitz** [comment]
Pulling apart `init_cache` and `add_blockdevs` in the sim and strat engine now that #1828 has been merged.

**Comment by jbaublitz** [comment]
Rebased. Some major changes will need to be done here after #1847 is merged.

**Comment by mulkieran** [comment]
This is more-or-less blocked by #1822 work.

**Comment by jbaublitz** [comment]
Updated to use `key_desc` as will be necessary based on #1908.

**Pull request closed without merging**
