### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**
Found via `typos --format brief`

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran I'm mostly interested in whether we could maybe put this in CI to avoid future typos.

**Comment by mulkieran** [comment]
> @mulkieran I'm mostly interested in whether we could maybe put this in CI to avoid future typos.

@jbaublitz My question, too! What provides typos ?

**Review by mulkieran — APPROVED** [review]

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Comment by kianmeng** [comment]
Let me know if a CI job is needed for https://github.com/crate-ci/typos. I can create a separate PR.

**Comment by mulkieran** [comment]
> Let me know if a CI job is needed for https://github.com/crate-ci/typos. I can create a separate PR.

Thanks! I had not known of typos until your PR. I'm trying out a basic attempt at incorporating into CI: #3262 ; I'll ask for your review when it's ready.

**Pull request merged**
