### PR TITLE
Remove plymouth service from generator

### LINKED ISSUE #3394: Remove plymouth-related code
Sub of https://github.com/stratis-storage/project/issues/640

### PR DESCRIPTION
**Pull request by mulkieran**
Closes #3394

### CODE REVIEW

**Comment by mulkieran** [comment]
Should we modify the unit to wait for something else? systemd-ask-password is also a service.

**Comment by mulkieran** [comment]
udev test failure unlikely to be real.

**Comment by jbaublitz** [comment]
@mulkieran I would strongly recommend waiting for systemd-ask-password. I tested it without systemd-ask-password and I think some of the errors we were bumping into when Matthias originally submitted the PR may have been due to that. Even if they weren't, if a new ordering constraint is introduced, it may cause our service to run before systemd-ask-password is ready and cause errors in the future without that dependency explicitly specified.

**Comment by mulkieran** [comment]
> @mulkieran I would strongly recommend waiting for systemd-ask-password. I tested it without systemd-ask-password and I think some of the errors we were bumping into when Matthias originally submitted the PR may have been due to that. Even if they weren't, if a new ordering constraint is introduced, it may cause our service to run before systemd-ask-password is ready and cause errors in the future without that dependency explicitly specified.

Agreed.

**Comment by mulkieran** [comment]
Closing, because I've transferred the issue.

**Pull request closed without merging**
