### PR TITLE
README.md(s) Minor updates

### PR DESCRIPTION
**Pull request by tasleson**
* Add blurb about missing dbus library for dbus-rs
* Misc. changes and improvements/clarifications

Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by trgill** [comment]
Can one of the admins verify this patch?

**Comment by mulkieran** [comment]
But I am puzzled by Jenkins' behavior...

**Comment by trgill** [comment]
@mulkieran Jenkins won't trigger a build unless the user has been added to an authorized list.  I just added @tasleson.

When someone that is not on the list opens a PR - Jenkins automatically posts: "Can one of the admins verify this patch?"

If we respond with "test this please" - it will kick off a build.  I'll try it now.

**Comment by trgill** [comment]
test this please

**Comment by trgill** [comment]
FYI - if "test this please" is anywhere in the message it will trigger the build.

**Comment by agrover** [comment]
👍 , merging as last reviewer. Thanks!!

**Pull request merged**
