### PR TITLE
Minor tweaks to GitHub Actions configuration file

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran I'm actually going to check if the `PATH` setting is necessary now that you've corrected `python_version` to `python-version`. That may have been the problem!

**Review by jbaublitz — CHANGES_REQUESTED** [review]
It looks like #2331 can successfully remove the `PATH` specification now that you've fixed `python-version`. Can you pull in that change? Then this looks good to go.

**Comment by jbaublitz** [comment]
I'm also going to try simplifying one more thing for the Python checks now that the Python installation is working.

**Comment by mulkieran** [comment]
Ok! Let me know when ready.

**Comment by jbaublitz** [comment]
@mulkieran Okay #2331 is all ready! I fixed the two workarounds that weren't actually necessary. There's just one more commit.

**Comment by mulkieran** [comment]
Ok! I'm ready too.

**Review by jbaublitz — APPROVED** [review]
Looks good!

**Pull request merged**
