### PR TITLE
Add some macros for when there is no return value.

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
These are good for when you want to use the original macros, but can't because there is no default return value. ```rename_filesystem``` is a good example.

**Comment by mulkieran** [comment]
@trgill @agrover review?

**Comment by agrover** [comment]
suggest updating this PR to use the new macros once #137 is merged.

**Comment by trgill** [comment]
:+1:  I'll merge this and then update my PR to use the macros.

**Pull request merged**
