### PR TITLE
Change type of value in pool map to concrete type.

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Does not compile:

```
[mulhern@dhcp-25-209 stratisd]$ cargo run
   Compiling stratisd v0.1.0 (file:///home/mulhern/my-contributions/stratisd)
src/sim_engine/engine.rs:69:44: 69:48 error: mismatched types [E0308]
src/sim_engine/engine.rs:69         self.pools.insert(name.to_owned(), pool);
                                                                       ^~~~
src/sim_engine/engine.rs:69:44: 69:48 help: run `rustc --explain E0308` to see a detailed explanation
src/sim_engine/engine.rs:69:44: 69:48 note: expected type `Box<sim_engine::pool::SimPool>`
src/sim_engine/engine.rs:69:44: 69:48 note:    found type `Box<engine::Pool>`
src/sim_engine/engine.rs:89:12: 89:23 error: mismatched types [E0308]
src/sim_engine/engine.rs:89         Ok(return_pool)
                                       ^~~~~~~~~~~
src/sim_engine/engine.rs:89:12: 89:23 help: run `rustc --explain E0308` to see a detailed explanation
src/sim_engine/engine.rs:89:12: 89:23 note: expected type `&mut Box<engine::Pool>`
src/sim_engine/engine.rs:89:12: 89:23 note:    found type `&mut Box<sim_engine::pool::SimPool>`
```

I can not explain either error.

**Comment by mulkieran** [comment]
The first error goes away, leaving:

```
[mulhern@dhcp-25-209 stratisd]$ cargo run
   Compiling stratisd v0.1.0 (file:///home/mulhern/my-contributions/stratisd)
src/sim_engine/engine.rs:89:12: 89:23 error: mismatched types [E0308]
src/sim_engine/engine.rs:89         Ok(return_pool)
                                       ^~~~~~~~~~~
src/sim_engine/engine.rs:89:12: 89:23 help: run `rustc --explain E0308` to see a detailed explanation
src/sim_engine/engine.rs:89:12: 89:23 note: expected type `&mut Box<engine::Pool>`
src/sim_engine/engine.rs:89:12: 89:23 note:    found type `&mut Box<sim_engine::pool::SimPool>`
error: aborting due to previous error
error: Could not compile `stratisd`.
```

**Comment by mulkieran** [comment]
We can tell the the compiler promotes a ```Box<SimPool>``` to a ```Box<Pool>``` without any help. Clearly it is the ```&mut``` that is making the diffrence, but I don't know why.

**Comment by mulkieran** [comment]
I am fairly confident that agrover's branch would have the same problem  if line https://github.com/stratis-storage/stratisd/pull/111/files#diff-50cfba3b084003ea8d21c66346be51beR23 were changed so that the map was to a concrete pool type instead of to Pool. In other contexts, the maps are to concrete types, but they can only get away with this because they are not retunrning a refrence to the object.

**Comment by agrover** [comment]
I got this to compile by not boxing the internal list, and returning a `&mut Pool` instead of `&mut Box<Pool>`. Try this?

https://github.com/agrover/stratisd/commit/4d295e5e0ebcf168da7fad4b33f701dc823e710c

**Comment by mulkieran** [comment]
superceded by #133

**Pull request closed without merging**
