### PR TITLE
Fallback to smaller request when extending the thin pool

### PR DESCRIPTION
**Pull request by mulkieran**
Instead of having a hard fail if the requested amount is not available, fall back on a smaller request.

Choosing to try for a smaller amount is the only reasonable course. However, this PR introduces the possibility of a situation where an amount was successfully allocated to a thin pool device but that amount was smaller than the calculated amount requested. This PR calls out that issue in a TODO, but does not address it. It is expected that it will be addressed in some form by subsequent PRs, including #1083.

### CODE REVIEW

**Comment by mulkieran** [comment]
Travis CI failure was spurious. stratisd failures were real, but due to a simple bug, now fixed, most likely.

**Comment by mulkieran** [comment]
Fixed another simple bug...

**Comment by mulkieran** [comment]
There was an error in ```test_meta_expand```, the subsequent errors seems spurious.

**Comment by mulkieran** [comment]
@agrover I've updated to get rid of ```fn try_to_allocate```.

**Comment by mulkieran** [comment]
@agrover 

It might be better to flatten out ```alloc_space``` into two separate methods:

1. alloc_one_segment_max -- which allocates just one, but falls back to smaller value if necessary
2. alloc_multiple_segments_exactly -- which allocates multiple segments, but fails if it can not allocate them all exactly

This would just require lifting the locally defined methods in ```alloc_space``` to the top level, getting rid of ```alloc_space``` entirely, and not using ```either```.

That seems less tortured. I believe you suggested it in our meeting anyway.

**Comment by agrover** [comment]
worth a shot!

**Comment by mulkieran** [comment]
Closing in favor of #1089.

**Pull request closed without merging**
