### PR TITLE
Work on engine state reporting

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to #1122
Related to #1784.
Resolves: https://github.com/stratis-storage/project/issues/93.

### CODE REVIEW

**Comment by jbaublitz** [comment]
Blocked by #1975

**Comment by jbaublitz** [comment]
CI is failing due to Github issues.

**Comment by bgurney-rh** [comment]
I sent a retry command to TravisCI and the cli-with-stratisd test; hopefully that allows the tests to re-run cleanly.

**Comment by jbaublitz** [comment]
Thank you, it looks like that worked!

**Comment by mulkieran** [comment]
@jbaublitz Please rebase when you get the chance.

**Comment by mulkieran** [comment]
The structure of this is fine. I do not know if there is a compelling case for the mock objects on the SimEngine, though. The internal structures of the SimEngine will vary a good deal from those of the StratEngine. The intended use is to allow person wanting to debug remotely or for sos reports to take a look at the StratEngine. So, having the SimEngine just return an empty report would be fine with me.

For the StratEngine, I would be happy merging just this outer skeleton as is; and filling in the remaining bits incrementally.

**Comment by mulkieran** [comment]
We decided in standup to defer this a bit longer. The reason is that it might make sense to implement json crate's Serialize and Deserialize tratis, rather than take the approach here.

We also discussed a bit about the SimEngine's implementation. We noted that there is already a mock-up of incomplete pools that went in with a previous commit. This gets moved around in this PR but basically remains the same. The key thing is not to spend too much effort on the sim engine.

Should the D-Bus always return its representation of ```None``` for the SimEngine? If we decide to do that, we could have it return ```None``` for the errored devices report as well. I'ld be happy with that. We should only spend time on the SimEngine reports if we can demonstrate a real advantage.

**Comment by jbaublitz** [comment]
Per our discussion in #1995, should I resume work on this?

**Comment by mulkieran** [comment]
> Per our discussion in #1995, should I resume work on this?

We should talk about it again in standup.

**Comment by jbaublitz** [comment]
Sounds good!

**Comment by jbaublitz** [comment]
I accidentally applied the most recent changes during a rebase so the first commit is a combination of the original PR and changes that I just made.

**Comment by jbaublitz** [comment]
TODO: Make sim_engine consistent with the strat_engine.

**Comment by jbaublitz** [comment]
I agree that we may have to diverge as we've done in other areas surrounding encryption in the sim_engine. I'm not determined to keep it identical, but it just seemed to make sense here as it was possible.

**Pull request closed without merging**
