### PR TITLE
Send correct interfaces for LockedPools property changed signal

### LINKED ISSUE #2923: Wrong interface name in PropertiesChanged signal when creating encrypted pool
stratisd 3.0.3

When creating a encrypted pool with Cockpit, we see the signal below.  This clearly tries to set the manager properties, but uses the `org.storage.stratis3.pool.r0` interface name.

This causes a "Uncaught TypeError: Cannot read properties of undefined (reading 'localeCompare')" error since Cockpit now treats the manager object as a pool, but it doesn't have any of the expected properties.

Tell me if you need a more concrete reproducer.

```
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=11  Timestamp="Thu 2022-02-10 13:32:50.831372 UTC"
  Sender=:1.0  Path=/org/storage/stratis3  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.0
  MESSAGE "sa{sv}as" {
          STRING "org.storage.stratis3.pool.r0";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "LockedPools";
                          VARIANT "a{sa{sv}}" {
                                  ARRAY "{sa{sv}}" {
                                          DICT_ENTRY "sa{sv}" {
                                                  STRING "e11eb60baf4348f48bba1e507faf3363";
                                                  ARRAY "{sv}" {
                                                          DICT_ENTRY "sv" {
                                                                  STRING "clevis_info";
                                                                  VARIANT "(bv)" {
                                                                          STRUCT "bv" {
                                                                                  BOOLEAN true;
                                                                                  VARIANT "(b(ss))" {
                                                                                          STRUCT "b(ss)" {
                                                                                                  BOOLEAN false;
                                                                                                  STRUCT "ss" {
                                                                                                          STRING "";
                                                                                                          STRING "";
                                                                                                  };
                                                                                          };
                                                                                  };
                                                                          };
                                                                  };
                                                          };
                                                          DICT_ENTRY "sv" {
                                                                  STRING "devs";
                                                                  VARIANT "aa{ss}" {
                                                                          ARRAY "a{ss}" {
                                                                                  ARRAY "{ss}" {
                                                                                          DICT_ENTRY "ss" {
                                                                                                  STRING "devnode";
                                                                                                  STRING "/dev/sda";
                                                                                          };
                                                                                          DICT_ENTRY "ss" {
                                                                                                  STRING "uuid";
                                                                                                  STRING "93d4e9c0526044a38a7491e0452add49";
                                                                                          };
                                                                                  };
                                                                          };
                                                                  };
                                                          };
                                                          DICT_ENTRY "sv" {
                                                                  STRING "key_description";
                                                                  VARIANT "(bv)" {
                                                                          STRUCT "bv" {
                                                                                  BOOLEAN true;
                                                                                  VARIANT "(bs)" {
                                                                                          STRUCT "bs" {
                                                                                                  BOOLEAN true;
                                                                                                  STRING "pool0";
                                                                                          };
                                                                                  };
                                                                          };
                                                                  };
                                                          };
                                                  };
                                          };
                                  };
                          };
                  };
          };
          ARRAY "s" {
          };
  };
```

### PR DESCRIPTION
**Pull request by mulkieran**
Closes #2923

### CODE REVIEW

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
@mvollmer Thanks for the issue. Would you like to test? We'll hold it until Friday afternoon our time.

**Review by mvollmer — APPROVED** [review]
Our test passes with this, and all the signals look like expected.  Thanks!

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
udev tests are stalling due to udev flakiness.

**Pull request merged**
