### PR TITLE
Update dependencies

### LINKED ISSUE #1496: proptest 0.9
Would be much appreciated :)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1496.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
CI fails because proptest macro doesn't work apparently?

**Comment by mulkieran** [comment]
Yeah, #1513 is also an attempt at this.

**Comment by GuillaumeGomez** [comment]
Considering the age of #1513, I thought it was abandoned... Should I close mine then?

**Comment by mulkieran** [comment]
Probably. There are three forces at work, proptest's goals, Fedora's need to move forward, and stratisd's need to be somewhat stable. Then the cargo dependency resolution dumps us in the soup. I'm not sure how we'll resolve it.

**Comment by mulkieran** [comment]
I'll close this, and we'll try again with the most simple possible Cargo.toml.

**Pull request closed without merging**
