### PR TITLE
Put startup actions into a separate module

### PR DESCRIPTION
**Pull request by mulkieran**
This is a minor PR which isolates startup actions for stratisd into a separate module. This is generally a good idea, because it increases clarity, but it is going to be more obviously helpful when handling errors.

It is cherry-picked from #1002.

### CODE REVIEW

**Comment by mulkieran** [comment]
Lock file still doing its locking job.

```
[root@localhost stratisd]#  ./target/x86_64-unknown-linux-gnu/debug/stratisd --sim --debug &
[1] 17959
 INFO 2018-07-02T16:04:56Z: stratisd: Using SimEngine
[root@localhost stratisd]#  ./target/x86_64-unknown-linux-gnu/debug/stratisd --sim --debug &
[2] 17966
Error: Daemon already running with pid: 17959
[2]+  Exit 1                  ./target/x86_64-unknown-linux-gnu/debug/stratisd --sim --debug
[root@localhost stratisd]# ps auxw | grep stratisd
mulhern  14677  0.2  0.0 160208  9320 pts/9    S+   11:57   0:00 vim src/bin/stratisd.rs
root     17959  0.0  0.0  47156  8684 pts/5    S    12:04   0:00 ./target/x86_64-unknown-linux-gnu/debug/stratisd --sim --debug
root     17974  0.0  0.0 119468   888 pts/5    S+   12:05   0:00 grep --color=auto stratisd
```

**Comment by agrover** [comment]
I'm not seeing the standalone value, so let's look at this in the context of #1002 ok? Thanks.

**Comment by mulkieran** [comment]
I guess this is blocked by #1023.

**Comment by mulkieran** [comment]
By #1026 as well, really, since that alters how logging, one of the prelude tasks, is done.

**Comment by mulkieran** [comment]
This is blocked by #1391. It already has conflicts with existing master, but when #1391 goes in those conflicts will change into other conflicts. Might as well wait.

**Comment by mulkieran** [comment]
Superceded by #1514.

**Pull request closed without merging**
