### PR TITLE
Invoke xfs_db directly

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #1251 .

### CODE REVIEW

**Comment by mulkieran** [comment]
We might have fewer constraints on how we run testing w/ this, as well. One of the reasons we can't run many tests on Travis is that Travis has an old version of ```xfs_admin``` that does not allow setting the UUID. If it has a version of ```xfs_db``` that does allow setting the UUID, than we can revive those tests on Travis, which will probably be a good thing. This might be worth checking out.

**Comment by mulkieran** [comment]
test failed, I expect -x flag is actually needed.

**Comment by agrover** [comment]
`man xfs_db` says:
```
xfs_db is used to examine an XFS filesystem. Under  rare  circumstances
it  can also be used to modify an XFS filesystem, but that task is nor‐
mally left to xfs_repair(8) or to scripts such as xfs_admin(8) that run
xfs_db.
```
I think we should keep using xfs_admin for now.

**Comment by mulkieran** [comment]
The "-x" flag fixed it. It's funny that when we call ```xfs_admin``` we immediately are promoted to "expert" ```xfs_db``` users in almost all cases.

Pros and cons of switching to invoking ```xfs_db``` directly that I am aware of.

Pros:
* #1251 would have been impossible, so it would never have been filed. stratisd will succeed in making snapshots, even in a situation where the environment is kind of messed up.
* We expect to have stratisd running in situations where PATH variable is not even set. ```xfs_admin``` is a shell script which redirects to executables in all or almost all cases. It relies implicitly on the PATH variable being set. Calling ```xfs_admin``` in these circumstances will always fail to work, given the code as it is now. Note: This point is a bit more complicated than it looks, as one can make arguments about the probability that stratisd will be making snapshots in these early environments, which is kind of low, AFAIK. But that discussion could get really complicated, so I won't follow it up here.
* Knowledge of what we're actually doing, i.e., invoking ```xfs_db``` with "-x" flag set.

Cons:
None

Note: Being able to run more tests on Travis than formerly was a red herring. Switching to invoking ```xfs_db``` directly will not change anything there, AFAICT.

**Comment by mulkieran** [comment]
We agreed that this was actually 1.0.1 in standup, so moving it there.

**Pull request merged**
