### PR TITLE
Master udev

### PR DESCRIPTION
**Pull request by mulkieran**
Supercedes #1005.

### CODE REVIEW

**Comment by mulkieran** [comment]
This is not complete. Is everybody on board w/ making the udev context a global variable?

**Comment by agrover** [comment]
I'd like a little more explanation -- the commitlog wasn't quite enough for me to understand the rationale.

**Comment by mulkieran** [comment]
I was only asking about the udev context, i.e., does  anybody have any objections to making it global? There's really not much more to say in the commit message than I have said.

**Comment by mulkieran** [comment]
Superceded, closing.

**Pull request closed without merging**
