### PR TITLE
Use richer Display for devicemapper Core errors

### PR DESCRIPTION
**Pull request by mulkieran**
Addresses: #1160.

### CODE REVIEW

**Comment by agrover** [comment]
#1166 also made BUSY a DbusErrorEnum::ERROR instead of INTERNAL_ERROR. This PR doesn't. I have opened #1181 and suggest it be resolved as part of this PR or a subsequent one.

**Comment by agrover** [comment]
@mulkieran hi, please review and consider #1194?

**Comment by mulkieran** [comment]
@agrover I'ld rather deal with the Enum stuff separately. We once had a clear meaning for ```INTERNAL_ERROR``` which was "internal error". I think this inevitably rotted because of our type-based approach to generating D-Bus error codes. I don't mind throwing errors into other categories, but it is a separate issue.

**Comment by agrover** [comment]
Ok sounds good.

**Pull request merged**
