### PR TITLE
Version 3.7.0

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Failures with testing repo and with stratis-cli are expected...

**Comment by mulkieran** [comment]
should pass stratis-cli tests

**Comment by mulkieran** [comment]
TMT failures can be ignored, so everything is passing.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
With the removal of the TEMPORARY commit stratis-cli tests will fail. We actually need to make that redirect permanent, though.

**Comment by mulkieran** [comment]
Redirect to stratis-cli rebase branch now permanently part of this PR. No other changes. testing changes are still just a PR, so expect failures on those.

**Comment by mulkieran** [comment]
TMT framework errors again...

**Pull request merged**
