### PR TITLE
Complete cache development

### PR DESCRIPTION
**Pull request by mulkieran**
Supercedes: #811.
Resolves: #631.

### CODE REVIEW

**Comment by mulkieran** [comment]
Code exactly the same as #811 (except for "Correct specification for ```get_blockdevs``` which removes one line of header comments.

**Comment by mulkieran** [comment]
@agrover review, please?

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Jenkins got stuck during cleanup, rebooted.

**Comment by mulkieran** [comment]
I accidentally introduced a fix while rebasing; two resume's in DataTier::add(). There should have been a test failure w/out the fix; I'm extending a test to make sure the code path is properly covered.

**Comment by mulkieran** [comment]
review, please?

**Comment by agrover** [comment]
looks good! Thanks for all the work that went into this PR!

**Pull request merged**
