### PR TITLE
Support snapshot revert operation

### PR DESCRIPTION
**Pull request by mulkieran**
Closes https://github.com/stratis-storage/stratisd/issues/3621
Closes https://github.com/stratis-storage/stratisd/issues/3622

### CODE REVIEW

**Comment by martinpitt** [comment]
Ech, can we please stop breaking rawhide in new an "interesting" ways every *censored* day? I'm still catching up with the fallout from the firewalld/selinux debacle..

```
+ chpasswd
chpasswd: (user root) pam_chauthtok() failed, error:
Authentication token manipulation error
chpasswd: (line 1, user root) password not changed
```

Again, clearly not your fault. I'm still busy with investigating/reporting the other regressions from last night, so if someone else could have a look that'd be nice. However, as #3653 went green, it's worth retrying.

**Comment by martinpitt** [comment]
The timing coincides with https://bodhi.fedoraproject.org/updates/FEDORA-2024-26a844bb1c . This also happens in podman PRs, e.g. https://github.com/containers/podman/pull/23274 or https://github.com/containers/podman/pull/23275 . 

Trivially reproducible in a rawhide VM with updating shadow-utils. With shadow-utils-2:4.15.1-8.fc41.x86_64 (*not* the latest version from that bodhi update, that's -9):

```
# echo root:foobar | chpasswd
chpasswd: (user root) pam_chauthtok() failed, error:
Authentication token manipulation error
chpasswd: (line 1, user root) password not changed
```

That most recent bodhi update reverted the change again:
```
dnf update https://kojipkgs.fedoraproject.org//packages/shadow-utils/4.15.1/9.fc41/x86_64/shadow-utils-4.15.1-9.fc41.x86_64.rpm
```
and with that it works. So please retry.

**Comment by martinpitt** [comment]
I hacked around the shadow-utils b0rkage in https://github.com/cockpit-project/cockpit/pull/20802 . Can you please retry the failed tests (or ignore the rawhide failures if you don't care)?

**Comment by mulkieran** [comment]
rebased. This was just a conflict w/ the filesystem metadata PR, so it was not a lot of work to resolve the conflicts.

**Comment by mulkieran** [comment]
I think that likely we'll need to expose the message method in devicemapper and that that will be the most efficient and easiest thing.

**Comment by mulkieran** [comment]
Now running into ENOSPC on both ubuntu and fedora.

**Comment by mulkieran** [comment]
On both Fedora and Ubuntu, loop_test_rename is just hanging...

**Comment by mulkieran** [comment]
Huzzah! At least the thinpool checks are succeeding (by reducing the size of the filesystems).

**Comment by mulkieran** [comment]
Next step is to set the XFS filesystem UUID.

**Comment by mulkieran** [comment]
rebased. Need to fix up engine level unit tests.

**Comment by mulkieran** [comment]
See if engine tests fail

**Comment by mulkieran** [comment]
Now all existing tests are succeeding again. What happens if we add the revert test back in again?

**Comment by mulkieran** [comment]
The initial pool is not created in the test. We will give up on the revert Rust unit test, and test it externally, instead.

**Comment by mulkieran** [comment]
More boring type errors to fix

**Comment by bmr-cymru** [comment]
Setting/clearing the `MergeScheduled` property and applying the merge the next time the pool is set up is all working well with the current branch. I've added support to the `snapm` Stratis plugin and tested that we get the expected behaviour from a revert operation.

I know  we discussed this previously but now that I've had a chance to test it out some more I'm unsure about the cleaning up of the origin links after the revert in commit b081b6563f9809033a2bccc8284f20b0908df28f:

```
If a snapshot was taken after the one reverted to, remove its origin
field.

If a snapshot was reverted, any snapshot that points at it should have
its origin field removed.
```

1. I think for the first case it may make more sense to leave the origin set as it is: even though the snapshot was taken at a later point in time it is still a snapshot of the now-reverted origin. Since revert on thin is just a case of switching one `thin_id` address space for another the sequence of snapshot creation doesn't really matter.

This would be better for `snapm`'s uses since we use `Origin` to identify snapshots volumes, so the current behaviour causes us to lose track of snapshot set members when an earlier snapshot set is reverted:

```
# Create two snapshot sets:
root@localhost:~/src/git/snapm# snapm snapset create stratis1 /opt /srv
SnapsetName:      stratis1
MountPoints:      /opt, /srv
NrSnapshots:      2
Time:             2024-09-05 17:43:24
UUID:             c9ccc991-c6b3-539f-9273-21e5fc1cb1ce
Status:           Active
Autoactivate:     yes
Bootable:         no
root@localhost:~/src/git/snapm# snapm snapset create stratis2 /opt /srv
SnapsetName:      stratis2
MountPoints:      /opt, /srv
NrSnapshots:      2
Time:             2024-09-05 17:43:29
UUID:             c4c11f79-e15d-51b8-a4a5-951471699a4d
Status:           Active
Autoactivate:     yes
Bootable:         no
root@localhost:~/src/git/snapm# snapm snapset list
SnapsetName  Time                 NrSnapshots Status  MountPoints             
stratis1     2024-09-05 17:43:24            2 Active  /opt, /srv              
stratis2     2024-09-05 17:43:29            2 Active  /opt, /srv              

# Revert the first snapshot set:
root@localhost:~/src/git/snapm# snapm snapset revert stratis1
WARNING - Snaphot set stratis1 is in use: reboot required to complete revert
root@localhost:~/src/git/snapm# umount /opt /srv
root@localhost:~/src/git/snapm# stratis pool stop --name p1
root@localhost:~/src/git/snapm# stratis pool start --name p1

# The second snapshot set is now "orphaned":
root@localhost:~/src/git/snapm# snapm snapset list
SnapsetName  Time                 NrSnapshots Status  MountPoints             
root@localhost:~/src/git/snapm# stratis filesystem
Pool   Filesystem                             Total / Used / Free / Limit        Device                                                 UUID                                
p1     fs1                                    1 GiB / 73 MiB / 951 MiB / None    /dev/stratis/p1/fs1                                    590756f3-1eaf-47db-8dbb-224b3c5c038c
p1     fs1-snapset_stratis2_1725554609_-opt   1 GiB / 73 MiB / 951 MiB / None    /dev/stratis/p1/fs1-snapset_stratis2_1725554609_-opt   94e61615-b7d7-4ac6-8b1e-f8260908b539
p1     fs2                                    2 GiB / 73 MiB / 1.93 GiB / None   /dev/stratis/p1/fs2                                    9db8871e-ff2e-479b-9575-85f215553a78
p1     fs2-snapset_stratis2_1725554609_-srv   2 GiB / 73 MiB / 1.93 GiB / None   /dev/stratis/p1/fs2-snapset_stratis2_1725554609_-srv   6a1fb22d-aec8-47b6-af34-3ba3518376b8
```

This leaves the user unable to manage the snapshots via `snapm` and prevents the snapshot being reverted into the origin. If the origin link was maintained the user would be able to revert or delete the snapshot set via `snapm` as required.

Looking at LVM2 for comparison it's a bit inconsistent - for COW snapshots the origin of other snapshots is preserved after the merge operation but for thin it behaves similarly to the current Stratis implementation: the origin field of _all_ other snapshots is cleared and they become "normal" thin LVs. This seems to have caused some confusion for users in the past and there was a proposal a while ago to add a new `--keep-origin` option to maintain the link.

2. In the second case I think it would be better to set the origin of any snapshots-of-snapshots to the reverted origin UUID. This again allows us to still detect them as snapshots in `snapm` and would allow them to be reverted into the origin (which seems like a valid operation since the content is a snapshot of the data that exists on that device after the revert).

LVM2 does do this for thin snapshots-of-snapshots: the origin is updated following the merge to point to the merged origin volume:

```
root@localhost:~/src/git/stratis-cli# lvs
  LV                VG     Attr       LSize  Pool  Origin      Data%  Meta%  Move Log Cpy%Sync Convert
  pool0             fedora twi-aotz--  2.00g                   6.31   12.21                           
  test0             fedora Vwi-aotz--  1.00g pool0             6.32                                   
  test0-snap1       fedora Vwi---tz-k  1.00g pool0 test0                                              
  test0-snap1-snap1 fedora Vwi---tz-k  1.00g pool0 test0-snap1                                        

root@localhost:~/src/git/snapm# lvconvert --merge fedora/test0-snap1
  Volume fedora/test0-snap1 replaced origin fedora/test0

root@localhost:~/src/git/stratis-cli# lvs
  LV                VG     Attr       LSize  Pool  Origin Data%  Meta%  Move Log Cpy%Sync Convert
  pool0             fedora twi-aotz--  2.00g              6.31   12.21                           
  test0             fedora Vwi-a-tz--  1.00g pool0        6.32                                   
  test0-snap1-snap1 fedora Vwi---tz-k  1.00g pool0 test0                                         
```

**Comment by mulkieran** [comment]
(1) is done

**Comment by mulkieran** [comment]
For (2), the only issue is whether, if we do it, we ought to make ```destroy_filesystems``` patch up the graph, also. In both cases, we can have origin0, snap1, and snap1_a, where snap1_a is a snap of snap1. 

For the revert case, snap1 overwrites origin1, and the proposal is that snap1_a's origin should be changed to origin0, instead of being set to None, as it is now.

For the destroy case, if snap1 is destroyed, should snap1_a's origin be changed to origin0? It is currently set to None.

**Comment by mulkieran** [comment]
(2) is done

**Comment by mulkieran** [comment]
Another change is implemented. If reverting snap1_a into snap_1, the origin field is set to origin0, not to None as formerly.

**Comment by mulkieran** [comment]
I think we should make the  filesystem_destroy operation patch up the origin as well, to make it congruent with revert behavior. But that's more of a pain, because of the D-Bus.

**Comment by bmr-cymru** [comment]
> I think we should make the filesystem_destroy operation patch up the origin as well, to make it congruent with revert behavior. But that's more of a pain, because of the D-Bus.

I think that makes sense. I'll try to get these changes tested in my snapshot manager VMs.

**Pull request closed without merging**
