### PR TITLE
Add some testing to project and CI

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review?

This does not actually do much, but it does show that we can do testing, even quickcheck style, and include it in CI.

**Comment by trgill** [comment]
:+1:

**Comment by agrover** [comment]
👍 

So we're past the issue in #90?

**Comment by mulkieran** [comment]
@agrover: We can't do tests on the whole thing unless it is a library. We can do unit tests at every level of module and submodule, which is almost like doing integration tests. It does give us an incentive to organize modules and submodules carefully, to facilitate those tests.

**Pull request merged**
