### PR TITLE
Remove unnecessary clippy allows for new_ret_no_self

### PR DESCRIPTION
**Pull request by lleshchi**
Related stratis-storage/project#135

### CODE REVIEW

**Comment by jbaublitz** [comment]
ok to test

**Comment by bgurney-rh** [comment]
ok to test

**Comment by mulkieran** [comment]
The format's all good, but there's a similar thing going on in devicemapper, so I changed "closes" to "related". We'll have to figure out what to do with devicemapper code separately.

**Comment by mulkieran** [comment]
add to whitelist

**Pull request merged**
