### PR TITLE
Assert that libcryptsetup is always being called from the same thread

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to #2277

### CODE REVIEW

**Comment by jbaublitz** [comment]
I'm using this PR as a way to explore putting in a canary so that if we make future changes to how we're using the crypt module, we will be notified immediately if we attempt to accidentally access it from multiple threads as Rust will not protect us from that in this case.

**Comment by jbaublitz** [comment]
@bgurney-rh The failure appears to be a udev problem.

**Comment by bgurney-rh** [comment]
OK; I'm trying a re-run on a different test machine.

**Comment by jbaublitz** [comment]
@mulkieran Given that we've determined that the way we're currently doing things is safe even in the multithreading PR, do we want to put this into review to make sure that we never violate this contact?

**Comment by mulkieran** [comment]
> @mulkieran Given that we've determined that the way we're currently doing things is safe even in the multithreading PR, do we want to put this into review to make sure that we never violate this contact?

Yes, I think this is fine. Pls go ahead.

**Review by mulkieran — APPROVED** [review]

**Comment by jbaublitz** [comment]
This may be obsoleted by #2388. I'm leaving this open until we merge that one.

**Pull request closed without merging**
