### PR TITLE
github actions: move allowed_failures to nightly

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#244

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
Please work on inserting the clippy stable check in w/ the other allowed failures.

**Comment by bgurney-rh** [comment]
> Please work on inserting the clippy stable check in w/ the other allowed failures in nightly.

When I look at the `.github/workflows/main.yml' file, in the `checks:` section, the only other clippy tasks I see are for the current development compiler (currently 1.51.0).

**Comment by mulkieran** [comment]
The task is parameterized on the toolchain, (see https://github.com/stratis-storage/stratisd/pull/2554/files#diff-0d5658b415099a82c11c03a06ca4ec765b4003a1f4b2f3f1943980a882cf8aa6R52), so it should work correctly to just slot it into the matrix.

**Comment by bgurney-rh** [comment]
Ok, now I understand: the two jobs are so similar, we can run them as one.

**Pull request closed without merging**
