### PR TITLE
Add macro log events to pool create, rename, and destroy operations

### PR DESCRIPTION
**Pull request by bgurney-rh**
Supersedes #1895

### CODE REVIEW

**Comment by bgurney-rh** [comment]
Rebased.

**Comment by mulkieran** [comment]
I want to hold this until #1817 gets merged, as it changes the behavior of CreatePool a bit. Not guaranteed that there will be a necessary change to this PR, but waiting until it gets merged is less work than figuring out what will happen.

**Comment by mulkieran** [comment]
Might be blocked by #1877 as well, depending on the implementation choice.

**Comment by bgurney-rh** [comment]
> Please take a look at the changes suggested in #1915. Two are cosmetic, but the last commit is fairly significant, since it swaps the order of the action string and the other post-operation strings.

Looks good; I just applied them.

**Comment by mulkieran** [comment]
Superceded by #2288

**Pull request closed without merging**
