### PR TITLE
Adjust dbus-api names and permissions

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Note that the net line change is 0. This is because ```use``` directives are just moved down, from one ```mod.rs``` to the interface-specific ```mod.rs``` right below it.

**Comment by mulkieran** [comment]
Suitability for encryption PR can be tested out by looking at https://github.com/stratis-storage/stratisd/pull/1775/commits/5c2827d1a0e21be143b85771f0f803e4f65180db.

**Comment by jbaublitz** [comment]
I'll take a closer look at this tomorrow. Mainly I'll want to go over the import strategy and see how it lines up with what we already have. In terms of readability, I'm definitely happier with this.

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
