### PR TITLE
Do not reduce devnodes by the their device number

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Missing "!" in a test.

**Comment by jbaublitz** [comment]
Is it worth writing a test that attaches a device node to the same device major/minor numbers as an existing loopback device and passes both in to a `pool create` command?

**Comment by mulkieran** [comment]
> Is it worth writing a test that attaches a device node to the same device major/minor numbers as an existing loopback device and passes both in to a `pool create` command?

There probably is no time like the present for that.

**Comment by mulkieran** [comment]
A last-minute compiler error, sigh.

**Comment by mulkieran** [comment]
On both Travis and Jenkins mknod returns EEXIST. This is plausible on Jenkins, but it is really hard to believe that on Travis there is already a device node "/dev/junk". So, I think mknod, and not the mknod bindings, which are very simple, is behaving oddly, presumably returning EEXIST for some other reason of existance. Most likely we'll have to drop that additional testing bit until we can make the situation happen more easily.

**Comment by jbaublitz** [comment]
One comment I have that may be unrelated is that `mknod` takes an absolute path or else you will get a device node in your current directory.

**Comment by bgurney-rh** [comment]
Well, I see this on one of the jenkins test nodes:

```
$ ls -l workspace/stratisd/junk 
brwx------. 1 root root 252, 16 Mar 10 21:23 workspace/stratisd/junk
$ ls -l /dev/junk
brwx------. 1 root root 252, 16 Mar 10 20:53 /dev/junk
```

And those times are:
20:53 UTC: Add more testing for the duplicate device number case (commit: cc41298)
21:23 UTC: Try a relative path (commit: d01be56)

**Comment by mulkieran** [comment]
> Well, I see this on one of the jenkins test nodes:
> 
> ```
> $ ls -l workspace/stratisd/junk 
> brwx------. 1 root root 252, 16 Mar 10 21:23 workspace/stratisd/junk
> $ ls -l /dev/junk
> brwx------. 1 root root 252, 16 Mar 10 20:53 /dev/junk
> ```
> 
> And those times are:
> 20:53 UTC: Add more testing for the duplicate device number case (commit: [cc41298](https://github.com/stratis-storage/stratisd/commit/cc412983496609a2987b22e2c658daa2bab0338f))
> 21:23 UTC: Try a relative path (commit: [d01be56](https://github.com/stratis-storage/stratisd/commit/d01be56d4b60ae4919a93e8ec4dfcf18f57524bd))

I think you should feel free to remove those. But you should hardly expect the same error on Travis, because those machines should be fresh every time.

**Comment by bgurney-rh** [comment]
Okay, I removed the old device nodes.

**Comment by mulkieran** [comment]
Ok. I filed an issue for setting up the test: #1880; we know that the test succeeds.

**Comment by mulkieran** [comment]
Unchanged, back in review.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased...and removed ```pub``` modifiers from the test function introduced in the last commit.

**Pull request merged**
