### PR TITLE
Make sure clippy also checks bin/stratisd.rs

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
exactly the error expected. Now let's make sure clippy is running on stratisd.rs

**Comment by mulkieran** [comment]
And it's quite possible that the known clippy error blocks some unknown clippy error.

**Comment by mulkieran** [comment]
Wanna let #889 go first.

**Comment by agrover** [comment]
LGTM :+1:

**Pull request merged**
