### PR TITLE
Update for new version of nix in devicemapper

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
No code changes necessary.

**Comment by mulkieran** [comment]
Whoops. Getting nix compiler errors.

**Comment by mulkieran** [comment]
Restarting job, hopefully things will improve.

**Comment by agrover** [comment]
is this failing because of a bug in a nix macro?

**Comment by mulkieran** [comment]
I haven't reviewed, but remember that we don't want to merge this until we release a new version of devicemapper.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Dependencies got screwed up a bit. Right now, we want to put at devicemapper master branch.

**Comment by agrover** [comment]
tagged and published dm-rs 0.17.

**Comment by mulkieran** [comment]
Superceded by #783.

**Pull request closed without merging**
