### PR TITLE
Master devicemapper 0.14.0 next

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Looks like spurious failure.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by mulkieran** [comment]
@trgill It seems like stratisd-client-dbus tests are running against an older version of stratisd than this one, somehow.

**Comment by trgill** [comment]
@mulkieran looking at it now

**Comment by mulkieran** [comment]
Whoops, sorry , it's gone.

- mulhern



----- Original Message -----

**Comment by trgill** [comment]
@mulkieran ok - please let me know if you see any trouble.

**Comment by mulkieran** [comment]
@trgill Sorry, I was confused, problem still persists w/ #687, for instance.

**Comment by trgill** [comment]
@mulkieran no problem - I'll look at it now.

**Pull request merged**
