### PR TITLE
Dump more debug

### PR DESCRIPTION
**Pull request by tasleson**
Dump even more information when we fail to find the expected Stratis block devices.

Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by tasleson** [comment]
@agrover @trgill @mulkieran I would like to just get this into master so it runs for everyone's pull request to see if we can get this unit test to run without intermittent failures.

**Comment by mulkieran** [comment]
For some reason I thought this PR had 1 ack already when I acked it.

**Comment by tasleson** [comment]
Rebased

**Comment by tasleson** [comment]
Rebased

**Comment by tasleson** [comment]
Rebased

**Comment by tasleson** [comment]
@trgill  @mulkieran Once this passes CI I'll manually merge it

**Pull request merged**
