### PR TITLE
New cryptsetup version

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Comment by jbaublitz** [comment]
I've updated this to the current state of things in case you can merge it in the next week. If not, that's fine too and we can revisit it later.

**Comment by jbaublitz** [comment]
Actually it looks like the tests are failing in a real way. I'll investigate.

**Comment by jbaublitz** [comment]
I'm having a little bit of trouble understanding what's going on largely because `register_clevis_token()` appears to only fail in the test framework with `EINVAL` but succeeds when running stratisd regularly. Looking at the cryptsetup code, I see this: https://gitlab.com/cryptsetup/cryptsetup/-/blob/main/lib/luks2/luks2_token.c?ref_type=heads#L57-73. Theoretically the struct reference, the name, or the open method is being passed as NULL in the tests only for it to fail in this way.

**Comment by jbaublitz** [comment]
This is possibly related to the token handler being set multiple times. I'll try to fix it.

**Comment by mulkieran** [comment]
* f37:
  *  https://dashboard.packit.dev/results/copr-builds/1039757
  * https://dashboard.packit.dev/results/testing-farm/278324
  * https://artifacts.dev.testing-farm.io/54a73a1d-d60d-41c0-a586-6903e0ab833d

* f38:
  * https://dashboard.packit.dev/results/copr-builds/1039758
  * https://dashboard.packit.dev/results/testing-farm/278323
  * https://artifacts.dev.testing-farm.io/a827eed8-57fd-4e61-a6d0-864eb7c6b9d9

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
