### PR TITLE
Break out tests into separate categories

### PR DESCRIPTION
**Pull request by mulkieran**
The one test file was getting too long and confusing and there were too
many Stratis and devicemapper dependencies in it.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by trgill** [comment]
👍 when the conflicts are resolved.

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
