### PR TITLE
Master devicemapper 0.13 next

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased, pointing at devicemapper master.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
We will expect to merge this once new version of devicemapper is available. @agrover review?

**Comment by mulkieran** [comment]
rebased.

**Comment by agrover** [comment]
👍

**Pull request merged**
