### PR TITLE
Add optional devicemapper cache to pool physical layer

### PR DESCRIPTION
**Pull request by mulkieran**
Related: #486.

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover review? Especially check the comments in store.rs, as they represent a development plan of sorts.

**Comment by agrover** [comment]
store.rs looks like a good start. In future changes, I'm expecting to see a great deal of commonality between managing a group of data-tier blockdevs and a group of cache-tier blockdevs. For example, will Cache::new()'s cache param take a `Vec<StratBlockDev>` or similar, and will Cache have a second BlockDevMgr member for tracking them? Just curious if I'm envisioning where this is going correctly.

Next: Based on the assumption that for all the data tier blockdevs to be treated as the cachedev origin device, their usable space must be concatenated by way of a LinearDev, I wonder if it ends up making other things easier if we did this even in the no-cache-devices case.

Finally, "Store" is a pretty generic name. Is this more aptly called a "CachedBlockDevMgr" or something else a little more descriptive?

**Comment by mulkieran** [comment]
Regarding name of Store...it is not a good name. But "CachedBlockDevMgr" isn't so great either, because the cache is optional. Are there any other suggestions, @tasleson, @trgill?

**Comment by mulkieran** [comment]
> Next: Based on the assumption that for all the data tier blockdevs to be treated as the cachedev origin device, their usable space must be concatenated by way of a LinearDev, I wonder if it ends up making other things easier if we did this even in the no-cache-devices case.

Are you saying it might make sense to merge them all into a LinearDev and allocate from that?

**Comment by agrover** [comment]
> What that might mean is that BlockDevMgr::alloc_space() is simply eliminated entirely.

Thinking about it some more, not quite, because it still needs to track the actual blockdevs the allocations are on for the on-disk metadata. The common code would be a little more complex overall vs status quo: (creating concatenated linear (+complex), allocating from linear (-complex), tracking linear-to-blockdevmgr ranges (+complex)) but it would make the non-cache config look like an edge condition of a with-cache config, rather than an entirely separate code path (--complex).

Anyway, my recommendation would be to get with-cache working, feeling free to break non-cache, and then supporting non-cache should fall out of that (different physical top layers, like you said.)

**Comment by mulkieran** [comment]
I think we can abandon this in favor of #722.

**Pull request closed without merging**
