### PR TITLE
Refactor stratis-utils for better modularity and add facility for more convenient dispatch

### PR DESCRIPTION
**Pull request by mulkieran**
Related https://github.com/stratis-storage/project/issues/650

### CODE REVIEW

**Comment by mulkieran** [comment]
I think this is ready, but we should hold this until a little progress is made on https://github.com/stratis-storage/project/issues/650.

**Comment by mulkieran** [comment]
Failures are all infrastructure...

**Comment by mulkieran** [comment]
Still seems to install properly and all executables can still be invoked by their links.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
rebase

**Comment by mulkieran** [comment]
rebased again

**Pull request merged**
