### PR TITLE
On UnlockPool, start the pool directly

### LINKED ISSUE #3324: org.storage.stratis3.Manager.r1 UnlockPool does nothing anymore
Cockpit is still using the "r0" API level of org.storage.stratis3, but since Stratis 3.5.3 the UnlockPool method of the manager doesn't seem to actually unlock the pool.

```
# stratis pool list --stopped
Name    UUID                                   # Devices   Key Description   Clevis
pool0   2e609392-28d8-4f75-9e39-b3197c5ccf44           2   pool0             N/A   

# stratis key set pool0 --capture-key
Enter key data followed by the return key:

# busctl call org.storage.stratis3 /org/storage/stratis3 org.storage.stratis3.Manager.r0 UnlockPool ss 2e609392-28d8-4f75-9e39-b3197c5ccf44 keyring
(bas)qs true 2 "e7244a9d2516457ca8b44e92b570e23d" "26923cafb76c4386a5590e41555972c3" 0 "Ok"

# stratis pool list
Name   Total / Used / Free   Properties   UUID   Alerts

# stratis pool list --stopped
Name    UUID                                   # Devices   Key Description   Clevis
pool0   2e609392-28d8-4f75-9e39-b3197c5ccf44           2   pool0             N/A   

# busctl call org.storage.stratis3 /org/storage/stratis3 org.storage.stratis3.Manager.r2 StartPool 's(bs)' 2e609392-28d8-4f75-9e39-b3197c5ccf44 1 keyring
(b(oaoao))qs true "/org/storage/stratis3/0" 2 "/org/storage/stratis3/1" "/org/storage/stratis3/2" 1 "/org/storage/stratis3/3" 0 "Ok"

# stratis pool list
Name               Total / Used / Free    Properties                                   UUID   Alerts
pool0   7.97 GiB / 1.05 GiB / 6.92 GiB   ~Ca, Cr, Op   2e609392-28d8-4f75-9e39-b3197c5ccf44   WS001
```

As you can see, after calling r0.Unlock, the pool is still listed as stopped.  Calling r2.StartPool works as expected.

I guess Cockpit should catch up to at least "r2", but this looks like a unintended regression to me.

### PR DESCRIPTION
**Pull request by mulkieran**
Closes #3324

### CODE REVIEW

**Comment by mulkieran** [comment]
Expect tests that check the return value on the D-Bus for UnlockPool call to fail. That will only be legacy cli tests, if any, I think.

**Review by bgurney-rh — APPROVED** [review]
Successfully tested on commit 0ccf3b92

**Comment by mvollmer** [comment]
I am moving Cockpit to "r2" here: https://github.com/cockpit-project/cockpit/pull/18679, fyi. That should take the pressure of fixing #3324.

**Comment by mulkieran** [comment]
> I am moving Cockpit to "r2" here: [cockpit-project/cockpit#18679](https://github.com/cockpit-project/cockpit/pull/18679), fyi. That should take the pressure off of fixing #3324.

Ok!

**Comment by mulkieran** [comment]
Superceded by #3329

**Pull request closed without merging**
