### PR TITLE
Upgrade dbus requirement to 0.8

### LINKED ISSUE #1755: dbus-rs 0.7 came out in September; we should consider moving up at some time
We're currently pinned to 0.6.4 which came out in January 2019. We need to evaluate what the new version brings, as it has been under very active development; it is possible that it will bring us advantages which we can take advantage of on the upgrade.

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves #1755

### CODE REVIEW

**Comment by jbaublitz** [comment]
One note before I forget is that we may be able to get [this constant](https://github.com/stratis-storage/stratisd/pull/1837/files#diff-514a2718520e983db27476ed65de5994R13) from `dbus` instead of the corresponding `-sys` package so that we don't have to add an explicit crate dependency. This is the recommended way to do it if we can use the export from `dbus` like I think we can.

**Comment by mulkieran** [comment]
> One note before I forget is that we may be able to get [this constant](https://github.com/stratis-storage/stratisd/pull/1837/files#diff-514a2718520e983db27476ed65de5994R13) from `dbus` instead of the corresponding `-sys` package so that we don't have to add an explicit crate dependency. This is the recommended way to do it if we can use the export from `dbus` like I think we can.

I think we can!

**Comment by mulkieran** [comment]
I force-pushed in a moment of absent-mindedness...

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
