### PR TITLE
Unbox the values of the sim engine's pool.

### PR DESCRIPTION
**Pull request by mulkieran**
Adjust other methods accordingly.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
The ```list_``` and ```copy()``` methods are still a puzzle.

**Comment by agrover** [comment]
I think `copy` may be eligible for refactoring. Thoughts on this, as perhaps replacing `get_pool` and `list_pools` and letting us remove `copy`?

```
fn pools(&mut self) -> EngineResult<BTreeMap<String, &mut Pool>> {
        Ok(self.pools
            .iter_mut()
            .map(|x| (x.0.clone(), x.1 as &mut Pool))
            .collect())
    }
```

**Comment by mulkieran** [comment]
@agrover I think you're suggesting ```list_*s``` methods can be renamed to ```*s``` methods. Then ```get_*``` methods can be implemented in terms of the corresponding ```*s``` method. I'll give it a try.

**Comment by mulkieran** [comment]
@agrover @trgill review?

The label is still on there because I want to try to exercise these changes by expanding the sim engine a bit. OTOH, I'ld like feedback if anything seems really wrong.

I'm dubious about commit "Make the various list functions...", because I'm not sure that it would make sense to be able to mutate each object, and obviously it will make the method more difficult to use.

@agrover I don't know if you were actually suggesting this, but for efficiency reasons I'ld rather not get all the pools just to get the one pools I'm interested in. So, I left ```get_pool()``` alone, just changed its name to ```pool()```.

**Comment by agrover** [comment]
Great! Although I'd prefer `get_pool` kept its name, I think it better connotes there's a (possibly-failing) lookup happening. Also, can `*s()` methods fail? Do they still need to return EngineError?

Also great to see `copy` is no longer needed. I'm very positive about this PR.

**Comment by mulkieran** [comment]
@agrover for the sim engine the ```*s``` shoul dnever fail. I'm unsure abou tthe real engine, though.

**Comment by agrover** [comment]
They could return an empty collection but I don't think they could return an error. I think we are safe in assuming each engine is traversing its in-memory data structures to generate the returned items (should never fail) rather than doing I/O to build the list.

**Comment by mulkieran** [comment]
@agrover OK. That may be optimistic, but if it turns out wrong we can reverst it easily. I didn't try to make the dbus methods perfect, as my understanding is that they will go away anyway, wiht the ehlpf og GetMangeedObjects.

**Comment by agrover** [comment]
yup. :+1:

**Comment by mulkieran** [comment]
My hopes of finding anything wrong with this before noon are receding. @trgill Feel free to merge whenever you're ready.

**Pull request merged**
