### PR TITLE
Extend basic engine initialization test

### PR DESCRIPTION
**Pull request by mulkieran**
To verify that engine initialization succeeds when /dev/stratis is missing.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
We would like for this to fail.

**Comment by tasleson** [comment]
@mulkieran Looks good to me, please add a PR which creates the directory before we try to assemble the pools.

**Comment by agrover** [comment]
oops, I need to rebase.

**Comment by agrover** [comment]
passes now. I'm going to go ahead and merge this, then.

**Pull request merged**
