### PR TITLE
Update to 3.6.0

### PR DESCRIPTION
**Pull request by jbaublitz**
Required for part 2 of #3285

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran I think this is either a real failure in the way the test for signals is written or in my update. Do you know which it is?

**Comment by mulkieran** [comment]
@jbaublitz Plz rebase when you get the chance.

**Comment by mulkieran** [comment]
@jbaublitz Plz rebase.

**Comment by jbaublitz** [comment]
Rebased.

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
