### PR TITLE
Update stratis to clap v4

### PR DESCRIPTION
**Pull request by bmr-cymru**
Closes https://github.com/stratis-storage/project/issues/580

### CODE REVIEW

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
We don't have any tests to capture changes of behavior in stratis-min....it's something we have been meaning to do.

**Comment by bmr-cymru** [comment]
CI seems to be passing now. I'll wire the new stratis min tests up to a workflow tomorrow.

**Review by mulkieran — CHANGES_REQUESTED** [review]
@bmr-cymru It all looks good to me. Do you feel ready to hook it into a GitHub Action?

**Comment by bmr-cymru** [comment]
Rebased & squashed

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
