### PR TITLE
Add macro for retry operations and use for MDV unmount

### PR DESCRIPTION
**Pull request by jbaublitz**
Pulled out from #2814

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
I think that top rule of ```retry_operation``` must always be matched, so the desired expansion will not occur.

I'm not absolutely certain that a macro is the best choice. Would the retry crate be useful here[1]? It is already packaged in Fedora.

[1] https://crates.io/crates/retry

**Comment by mulkieran** [comment]
One more thing, the expand_macros test actually does expand, I think correctly. https://github.com/stratis-storage/stratisd/runs/5407644334?check_suite_focus=true.

**Comment by jbaublitz** [comment]
Okay this is ready for review!

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
@jbaublitz Plz sqash and I'll merge.

**Pull request merged**
