### PR TITLE
Require libcryptsetup bindings

### PR DESCRIPTION
**Pull request by mulkieran**
closes https://github.com/stratis-storage/project/issues/141

### CODE REVIEW

**Comment by mulkieran** [comment]
Jenkins may fail, as it is likely not to have the libcryptsetup bindings installed yet.

**Comment by jbaublitz** [comment]
> ~Jenkins may fail, as it is likely not to have the libcryptsetup bindings installed yet.~ Err, the dependencies for the libcryptsetup bindings. Travis may fail also.

We probably will need to get a newer version of libcryptsetup. See [this issue](https://github.com/stratis-storage/libcryptsetup-rs/issues/5) and [this comment](https://github.com/stratis-storage/libcryptsetup-rs/pull/4#issuecomment-585260142).

**Comment by mulkieran** [comment]
With these changes we expect Travis to succeed, but Jenkins still to fail.

**Comment by mulkieran** [comment]
Nope. We need to be more sophisticated.

**Comment by jbaublitz** [comment]
I think this is due to how Travis is parsed. If I recall correctly, Travis dedups keys in hashes so this would make sense that dbus is not found as it's probably using the most recent `apt` definition which only specifies the newer version of libcryptsetup.

**Comment by mulkieran** [comment]
Previous change seems to be working!

**Comment by mulkieran** [comment]
Travis problem is solved.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
