### PR TITLE
Fixes for new version of clippy

### PR DESCRIPTION
**Pull request by mulkieran**
clippy thinks it should be left out now.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Let's postpone even thinking about this until later.

**Comment by mulkieran** [comment]
rebased. I think it is time to pick this up again as we raise our minimum supported compiler version.

**Comment by mulkieran** [comment]
There's no reason not to merge this now, as it reduces the number of clippy errors by 1/2 and is virtually trivial.

**Comment by agrover** [comment]
Not waiting for Jenkins to merge since this PR is not actually making any changes to the code that might cause Jenkins to fail.

**Pull request merged**
