### PR TITLE
Miscellaneous (probably non-controversial) fixes

### PR DESCRIPTION
**Pull request by mulkieran**
It unclutters the calls and reduces the number of necessary conversions.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review?

These should probably go in soon, otherwise they will keep playing catchup w/ new code.

**Comment by mulkieran** [comment]
Whoops! Needs a fix.

**Comment by mulkieran** [comment]
Now good.

**Comment by agrover** [comment]
:+1:

**Comment by trgill** [comment]
:+1:

**Pull request merged**
