### PR TITLE
Standardize on canonicalized paths for devices

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes stratis-storage/project#314

### CODE REVIEW

**Comment by jbaublitz** [comment]
This is ready for final review.

**Comment by mulkieran** [comment]
@bgurney-rh This is a fix for stratis-storage/project#314. Can you run the test that disclosed the problem and verify improved behavior ?

**Review by mulkieran — COMMENTED** [review]
This looks to me like a very helpful simplification; I don't have any request.

**Comment by jbaublitz** [comment]
Do you want me to rebase?

**Review by bgurney-rh — APPROVED** [review]

**Review by mulkieran — CHANGES_REQUESTED** [review]
Please close this and open a new PR for final review.

**Pull request closed without merging**
