### PR TITLE
Jbaublitz issue project 171 pt2

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Test was a bit broken adding fixes to test and resubmitting.

**Comment by mulkieran** [comment]
Whoops. Another test error.

**Comment by mulkieran** [comment]
There is an error in the test, but it's interesting. I can't seem to get the D-Bus object for the object path of the newly created pool. It may be that the D-Bus object just hasn't been made available yet. The important thing is that both encrypted and non-encrypted are failing consistently in the same way.

**Comment by mulkieran** [comment]
Nope. Uninteresting error.

**Comment by mulkieran** [comment]
We have a real passing test!

**Comment by jbaublitz** [comment]
For the idempotency tweak, this would also return a successful value for unencrypted pools. I would think that we'd at least want to guard against unlocking an unencrypted pool if we're going to add this code.

**Comment by mulkieran** [comment]
> For the idempotency tweak, this would also return a successful value for unencrypted pools. I would think that we'd at least want to guard against unlocking an unencrypted pool if we're going to add this code.

We already go ahead and unlock sets of unencrypted devices.

I _think_ I would be more comfortable if we were consistent about that if we decided to do that. We can do a check of sets of devices. If they contain StratisInfos w luks field None, then they are unencrypted, and an error is returned. If already a setup pool which is not encrypted, then an error is returned. That leaves the non-error situation being only for pools that are encrypted or sets of devices where Stratis is managing the encryption.

But this is more complicated then the approach of unlocking anything that doesn't fail to unock.

**Comment by mulkieran** [comment]
@jbaublitz: The stratisd test had a kind of odd error in a crypt ownership test. It's hard to trace where it came from because of the nature of the test, but you might want to take a look. I don't think I've ever seen it before.

**Comment by mulkieran** [comment]
@jbaublitz: Ok, thanks. I'll keep my out for it, and maybe we can build up the test to make it easier to trace the source of that error if it happens again.

**Comment by mulkieran** [comment]
Last commit is not a lot of code added, but it is a significant new test. I have pretty strong expectations of it passing.

**Comment by mulkieran** [comment]
Test mistake.

**Comment by mulkieran** [comment]
And passing now.

**Comment by mulkieran** [comment]
Passing!

**Comment by mulkieran** [comment]
Merged  into other PRs.

**Pull request closed without merging**
