### PR TITLE
GetManagedObjects Refactoring (2)

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Supercedes #244.

**Comment by mulkieran** [comment]
@agrover The difference is that mountpoint and quota material is cleaned out of engine's Filesystem interface and implementation and that no mountpoint or quota related material is added to the DBus API.

**Comment by mulkieran** [comment]
+ 1 last commit

**Comment by agrover** [comment]
:+1: I'll merge shortly.

**Pull request merged**
