### PR TITLE
Add Cargo.lock to repo / Update Cargo.toml to include Mulhern

### PR DESCRIPTION
**Pull request by trgill**
rationale for adding Cargo.lock: we are an app, not a library:

http://doc.crates.io/guide.html#cargotoml-vs-cargolock

removed Cargo.lock from the .gitignore

Added Mulhern to authors line of the Cargo.toml

### CODE REVIEW

**Comment by trgill** [comment]
@agrover @mulkieran review?

**Comment by mulkieran** [comment]
Could you alphabetize the author names? That way their order looses all significance.

**Comment by trgill** [comment]
@mulkieran it is now sorted by email address

**Comment by mulkieran** [comment]
ok by me!

**Comment by agrover** [comment]
:+1:

**Pull request merged**
