### PR TITLE
Change how BlockDevMgr::last_update_time is initialized

### LINKED ISSUE #1509: Stratis pool becomes broken after being activated on machine with newer stratisd and incorrect date/time.
Hi, guys.

I have been experimenting with Stratis in new Linux distribs and encountered some problems with pool going into some kind of degraded state.
I've managed to get it 100% reproducible, though it requires rather complex configuration.

Basically, I have 2 machines, one with RHEL 8 Beta (with stratisd 1.0.0) and the other one with Fedora 30 Beta (stratisd 1.0.3).
**Machine with Fedora 30 has time set in the past** (doesn't matter, a few hours or a year).
Steps are the following:
1. Create a simple stratis pool on one disk on RHEL machine
````
[root@localhost ~]# stratis pool list
Name       Total Physical Size  Total Physical Used
rh8pool              16.00 GiB             1.12 GiB
[root@localhost ~]# stratis filesystem list
Pool Name  Name    Used     Created            Device
rh8pool    testfs  546 MiB  May 01 2019 20:28  /dev/stratis/rh8pool/testfs
rh8pool    lalala  546 MiB  May 01 2019 20:28  /dev/stratis/rh8pool/lalala
[root@localhost ~]# stratis blockdev list
Pool Name  Device Node    Physical Size       State  Tier
rh8pool    /dev/sdb1              4 GiB  Not-in-use  Data
rh8pool    /dev/sdb2          12.00 GiB      In-use  Data
````

2. Turn off the machine, detach the disk and attach it to the Fedora machine
3. The pool becomes active and on the first glance everything looks OK, all devices are activated and file systems are mountable.
````
sdb                                                                8:16   0    16G  0 disk
├─sdb1                                                             8:17   0     4G  0 part
│ └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-physical-originsub
│                                                                253:3    0    16G  0 stratis
│   ├─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thinmeta
│   │                                                            253:4    0    16M  0 stratis
│   │ └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool
│   │                                                            253:6    0    16G  0 stratis
│   │   ├─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-2310877ed848427bbbcf76d7af3fe80a
│   │   │                                                        253:8    0     1T  0 stratis
│   │   └─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-9dffae3e2e2b40ee9f0190331a28a937
│   │                                                            253:9    0     1T  0 stratis
│   ├─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thindata
│   │                                                            253:5    0    16G  0 stratis
│   │ └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool
│   │                                                            253:6    0    16G  0 stratis
│   │   ├─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-2310877ed848427bbbcf76d7af3fe80a
│   │   │                                                        253:8    0     1T  0 stratis
│   │   └─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-9dffae3e2e2b40ee9f0190331a28a937
│   │                                                            253:9    0     1T  0 stratis
│   └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-mdv
│                                                                253:7    0    16M  0 stratis
└─sdb2                                                             8:18   0    12G  0 part
  └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-physical-originsub
                                                                 253:3    0    16G  0 stratis
    ├─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thinmeta
    │                                                            253:4    0    16M  0 stratis
    │ └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool
    │                                                            253:6    0    16G  0 stratis
    │   ├─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-2310877ed848427bbbcf76d7af3fe80a
    │   │                                                        253:8    0     1T  0 stratis
    │   └─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-9dffae3e2e2b40ee9f0190331a28a937
    │                                                            253:9    0     1T  0 stratis
    ├─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thindata
    │                                                            253:5    0    16G  0 stratis
    │ └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool
    │                                                            253:6    0    16G  0 stratis
    │   ├─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-2310877ed848427bbbcf76d7af3fe80a
    │   │                                                        253:8    0     1T  0 stratis
    │   └─stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-9dffae3e2e2b40ee9f0190331a28a937
    │                                                            253:9    0     1T  0 stratis
    └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-mdv
                                                                 253:7    0    16M  0 stratis
sr0                                                               11:0    1 638.3M  0 rom     /run/media
````
At the same time, Stratis itself does not see the pool:
````
[root@localhost ~]# stratis pool
Name    Total Physical Size  Total Physical Used
[root@localhost ~]# stratis pool list
Name    Total Physical Size  Total Physical Used
[root@localhost ~]# stratis blockdev list
Pool Name  Device Node    Physical Size  State  Tier
[root@localhost ~]# stratis filesystem list
Pool Name  Name  Used  Created  Device  UUID
[root@localhost ~]#
````
In syslog we see some warnings:
````
[root@localhost ~]# journalctl -b | grep 'stratisd\|device-mapper'
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: bcf7b4d9-8a28-4e58-a602-834045a6d604, devnodes: /dev/sdb1): reason: Engine(Invalid, \"UUIDs of devices found (9471d4edc9474a70bd85456d49eb9625) did not correspond with UUIDs specified in the metadata for this group of devices (7ab46956b38e4566a0c2dc3e00ebb848, 9471d4edc9474a70bd85456d49eb9625)\")")
Apr 15 00:01:02 localhost.localdomain kernel: device-mapper: thin: Data device (dm-5) discard unsupported: Disabling discard passdown.
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  INFO libstratis::engine::strat_engine::thinpool::thinpool: Attempting to extend thinpool data sub-device belonging to pool bcf7b4d98a284e58a602834045a6d604 by 29767680 sectors
Apr 15 00:01:02 localhost.localdomain kernel: device-mapper: thin: Data device (dm-5) discard unsupported: Disabling discard passdown.
Apr 15 00:01:02 localhost.localdomain kernel: device-mapper: thin: 253:6: growing the data device from 1792 to 16327 blocks
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  INFO libstratis::engine::strat_engine::thinpool::thinpool: Extended thinpool data sub-device belonging to pool with uuid bcf7b4d98a284e58a602834045a6d604 by 29767680 sectors
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 7
Apr 15 00:01:02 localhost.localdomain kernel: device-mapper: thin: Data device (dm-5) discard unsupported: Disabling discard passdown.
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  INFO libstratis::engine::strat_engine::thinpool::thinpool: Data tier percent used: 7
Apr 15 00:01:02 localhost.localdomain kernel: device-mapper: thin: Data device (dm-5) discard unsupported: Disabling discard passdown.
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: bcf7b4d9-8a28-4e58-a602-834045a6d604, devnodes: /dev/sdb1 ,/dev/sdb2): reason: Engine(Error, \"Failed to save metadata to even one device in pool\")")
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: bcf7b4d9-8a28-4e58-a602-834045a6d604, devnodes: /dev/sdb1 ,/dev/sdb2): reason: DM(Dm(Invalid, \"Specified new table \\\"LinearDevTargetTable { table: [TargetLine { start: Sectors(0), length: Sectors(3768320), params: Linear(LinearTargetParams { device: Device { major: 8, minor: 18 }, start_offset: Sectors(8192) }) }] }\\\" does not match kernel table \\\"LinearDevTargetTable { table: [TargetLine { start: Sectors(0), length: Sectors(25155584), params: Linear(LinearTargetParams { device: Device { major: 8, minor: 18 }, start_offset: Sectors(8192) }) }, TargetLine { start: Sectors(25155584), length: Sectors(8380416), params: Linear(LinearTargetParams { device: Device { major: 8, minor: 17 }, start_offset: Sectors(8192) }) }] }\\\"\"))")
Apr 15 00:01:02 localhost.localdomain stratisd[576]:  WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: bcf7b4d9-8a28-4e58-a602-834045a6d604, devnodes: /dev/sdb1 ,/dev/sdb2): reason: DM(Dm(Invalid, \"Specified new table \\\"LinearDevTargetTable { table: [TargetLine { start: Sectors(0), length: Sectors(3768320), params: Linear(LinearTargetParams { device: Device { major: 8, minor: 18 }, start_offset: Sectors(8192) }) }] }\\\" does not match kernel table \\\"LinearDevTargetTable { table: [TargetLine { start: Sectors(0), length: Sectors(25155584), params: Linear(LinearTargetParams { device: Device { major: 8, minor: 18 }, start_offset: Sectors(8192) }) }, TargetLine { start: Sectors(25155584), length: Sectors(8380416), params: Linear(LinearTargetParams { device: Device { major: 8, minor: 17 }, start_offset: Sectors(8192) }) }] }\\\"\"))")
Apr 15 00:07:59 localhost.localdomain stratisd[576]:  INFO stratisd: Dump timer expired, dumping state
Apr 15 00:07:59 localhost.localdomain stratisd[576]: DEBUG stratisd: Engine state:
Apr 15 00:07:59 localhost.localdomain stratisd[576]: StratEngine {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:     pools: {},
Apr 15 00:07:59 localhost.localdomain stratisd[576]:     incomplete_pools: {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         bcf7b4d9-8a28-4e58-a602-834045a6d604: {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             Device {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:                 major: 8,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:                 minor: 17
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             }: "/dev/sdb1",
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             Device {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:                 major: 8,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:                 minor: 18
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             }: "/dev/sdb2"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }
Apr 15 00:07:59 localhost.localdomain stratisd[576]:     },
Apr 15 00:07:59 localhost.localdomain stratisd[576]:     watched_dev_last_event_nrs: {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thindata"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-mdv"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "fedora-home"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thinmeta"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-private-bcf7b4d98a284e58a602834045a6d604-physical-originsub"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-9dffae3e2e2b40ee9f0190331a28a937"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "stratis-1-bcf7b4d98a284e58a602834045a6d604-thin-fs-2310877ed848427bbbcf76d7af3fe80a"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "fedora-swap"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0,
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         DmNameBuf {
Apr 15 00:07:59 localhost.localdomain stratisd[576]:             inner: "fedora-root"
Apr 15 00:07:59 localhost.localdomain stratisd[576]:         }: 0
Apr 15 00:07:59 localhost.localdomain stratisd[576]:     }
Apr 15 00:07:59 localhost.localdomain stratisd[576]: }
````
4. Now, if we reboot the machine or reattach the disk back to RHEL, **no pool is activated and devices are not set up, so any data on FS becomes inaccessible**.
````
sdb                                                                    8:16   0    16G  0 disk
├─sdb1                                                                 8:17   0     4G  0 part
└─sdb2                                                                 8:18   0    12G  0 part
  └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-physical-originsub
                                                                     253:2    0   1.8G  0 stratis
    ├─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thinmeta
    │                                                                253:3    0    16M  0 stratis
    │ └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool
    │                                                                253:5    0   1.8G  0 stratis
    └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-flex-thindata
                                                                     253:4    0   1.8G  0 stratis
      └─stratis-1-private-bcf7b4d98a284e58a602834045a6d604-thinpool-pool
                                                                     253:5    0   1.8G  0 stratis
sr0                                                                   11:0    1 638.3M  0 rom     /run/media/tester/Acronis Media
````
Syslog contains the following:
````
May 04 15:05:27 localhost.localdomain kernel: device-mapper: thin: Data device (dm-4) discard unsupported: Disabling discard pass
down.
May 04 15:05:27 localhost.localdomain kernel: device-mapper: thin: 253:5: pool target (1792 blocks) too small: expected 16327
May 04 15:05:27 localhost.localdomain kernel: device-mapper: table: 253:5: thin-pool: preresume failed, error = -22
May 04 15:05:27 localhost.localdomain stratisd[573]:  WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engi
ne(Error, "failed to set up pool for (pool UUID: bcf7b4d9-8a28-4e58-a602-834045a6d604, devnodes: /dev/sdb2 ,/dev/sdb1): reason: D
M(Core(Error(IoctlError(DeviceInfo { hdr: Struct_dm_ioctl { version: [4, 39, 0], data_size: 16384, data_start: 312, target_count:
 0, open_count: 0, flags: 0, event_nr: 0, dev: Device { major: 0, minor: 0 }, name: \"stratis-1-private-bcf7b4d98a284e58a60283404
5a6d604-thinpool-pool\", uuid: \"\" } }, Sys(EINVAL)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None }
 })))")
````

It looks like the main problem is caused by this:
````
WARN libstratis::engine::strat_engine::engine: no pool set up, reason: Engine(Error, "failed to set up pool for (pool UUID: bcf7b4d9-8a28-4e58-a602-834045a6d604, devnodes: /dev/sdb1 ,/dev/sdb2): reason: Engine(Error, \"Failed to save metadata to even one device in pool\")")
````

I've looked in the code and I may be wrong, but it seems that this behavior is caused by this check: https://github.com/stratis-storage/stratisd/blob/01835b44b85aaa88e049d2707ea37aa6e423481f/src/engine/strat_engine/backstore/metadata.rs#L618

I do understand that my configuration and use-case may seem synthetic and even bizarre, but in fact it is not that rare.
Time shifts happen all the time in multiboot configurations, with Windows storing local time in RTC by default.
This is an especially important case for live-cd/rescue-cd distributions, because they
1. Don't always know how to correctly interpret the time in RTC
2. May have Stratisd version different from the one that is present on the user's OS.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1509.

@mulkieran: Is it how you had it in mind?

### CODE REVIEW

**Comment by mulkieran** [comment]
ok to test

**Comment by mulkieran** [comment]
@GuillaumeGomez Thanks for the PR! You'll note that in ```BlockDevMgr::initialize``` ```last_update_time``` is set to ```None```.

This is more-or-less necessarily correct, because when the block devices belonging to the blockdevmgr are first claimed by stratisd, the actual value of the variable length metadata is not yet known. This metadata contains information about all sorts of higher-level devices that haven't yet been constructed.
So, the last_update_time must remain an ```Option```.

However, at some later time, stratisd may come up again, and see devices that have already been initialized, and construct a blockdevmgr to manage them. Currently, it, incorrectly, constructs the blockdevmgr with a ```last_update_time``` value of ```None```. It should, instead, find out the last update time from the existing metadata on the devices which it has been given.

I think that the area where the crucial mistake is made is really where ```StratPool::setup``` calls ```Backstore::setup``` with a ```last_update_time``` value of ```None```. That can't always be right.

I would encourage you to look at the method ```get_metadata```. This method is looking for the most recent variable length metadata written to all the devices. Unfortunately, having found the most recent value, it only return the metadata, and not the update time. If it can be expanded to return both values, then the value is available to ```StratPool::setup```.

I'm afraid that the solution is less localized than I thought, but I think that that is the right place to start.

**Comment by GuillaumeGomez** [comment]
I'll take a look.

**Comment by mulkieran** [comment]
Superceded by #1590.

**Pull request closed without merging**
