### PR TITLE
BDA::read change function return values

### PR DESCRIPTION
**Pull request by tasleson**
Change signature to return
(io::Result<[u8; SECTOR_SIZE]>, io::Result<[u8; SECTOR_SIZE]>) so
that we can distinguish the difference from an IO error and a
device that simply has nothing but zeros.

Addresses: https://github.com/stratis-storage/stratisd/issues/1016

Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by tasleson** [comment]
@mulkieran  FYI: The stray changes occurred by cargo fmt.  I'm guessing there is differences between 1.31.0 and 1.32.0, however I find it interesting that the PR passed all checks.

**Comment by mulkieran** [comment]
> @mulkieran FYI: The stray changes occurred by cargo fmt. I'm guessing there is differences between 1.31.0 and 1.32.0, however I find it interesting that the PR passed all checks.

We should discuss at some time whether we should move the recommended development compiler up to 1.32. If we do, we should prepare the CI (and the README), first.

**Comment by tasleson** [comment]
@mulkieran Picked up your changes and rebased

**Comment by mulkieran** [comment]
I think this should go back in review slot.

**Comment by tasleson** [comment]
@mulkieran Picked up your latest changes & rebased.  Good catch on double IOError case.

**Pull request merged**
