### PR TITLE
Use cryptsetup 2.3 instead of 2.2 in Travis

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #1861 
Related to stratis-storage/project#152

### CODE REVIEW

**Comment by jbaublitz** [comment]
I found a linking bug if libcryptsetup 2.2 is installed. Because most system packages in Ubuntu depend on this, I need to add one more step to purge the system library or linking fails due to two present libcryptsetups of the same major version, one without `crypt_safe_free`. I'll rerequest review once I've confirmed that this `dpkg` command that I've found works locally also works for Travis based on how it behaves with #1847.

**Comment by mulkieran** [comment]
ok!

**Comment by jbaublitz** [comment]
Reproduced the issue and confirmed that this fixes it on my Ubuntu `bionic` VM. Will confirm on Travis.

**Comment by jbaublitz** [comment]
My best guess at why this was not visible before is that prior to today, the `crypt` module added in #1847 was all dead code and was probably pruned prior to linking. Now that I've begun using it in the `devices` module in #1847, linking was required.

**Comment by mulkieran** [comment]
Great! Glad we caught it here.

**Comment by jbaublitz** [comment]
Tests are now running in #1847. Back up for review.

**Comment by mulkieran** [comment]
Do you want to do anything about the dpkg warning ```dpkg: warning: unable to delete old directory '/etc/cryptsetup-initramfs': Directory not empty``` on the install command ```sudo dpkg -i ./cryptsetup_2.3.0-1_amd64.deb```?

**Comment by jbaublitz** [comment]
This doesn't concern me as we will never reboot and that is the only time initramfs would be necessary.

**Pull request closed without merging**
