### PR TITLE
Updates and tidies for new dbus-client-gen API

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
All the sim tests pass when run on my machine against the new version of dbus-client-gen w/ these changes.

```
[root@localhost client-dbus]# PYTHONPATH=./src STRATISD=/home/mulhern/my-contributions/stratisd/target/x86_64-unknown-linux-gnu/debug/stratisd make dbus-tests
py.test-3 ./tests/dbus
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/mulhern/my-contributions/stratisd/tests/client-dbus, inifile:
plugins: hypothesis-3.12.0
collected 40 items                                                              

tests/dbus/filesystem/test_rename.py ..
tests/dbus/manager/test_create.py ...
tests/dbus/manager/test_destroy.py .....
tests/dbus/manager/test_object_path.py ..
tests/dbus/manager/test_stratis.py ....
tests/dbus/pool/test_add_cache_devs.py ....
tests/dbus/pool/test_add_data_devs.py ..
tests/dbus/pool/test_create_filesystem.py .s...s
tests/dbus/pool/test_destroy_filesystem.py ....
tests/dbus/pool/test_rename.py ..
tests/dbus/pool/test_udev.py ssssss

==================== 32 passed, 8 skipped in 32.66 seconds ===============
```

**Comment by mulkieran** [comment]
Oh, and linting against new version also passed, so you can ignore the Travis lint failure.

**Comment by mulkieran** [comment]
Looks like stratisd python tests are correctly pulling from most recent released version, which is why they fail. stratis-cli also pulling from most recent released version, which is why it succeeds. So, seems like Jenkins tests are working correctly.

**Comment by agrover** [comment]
:+1: . What issues remain to block this PR?

**Comment by mulkieran** [comment]
I don't think there is anything more that needs to be done.

**Comment by mulkieran** [comment]
Maybe I can rerun the tests and get a different, succeeding, result.

**Comment by mulkieran** [comment]
Actually, might need a tweak to setup.py.

**Comment by mulkieran** [comment]
That cli-with-stratisd Jenkins job fails makes sense. But we should expect stratisd Jenkins job to succeed now.

**Comment by mulkieran** [comment]
All the unit tests passed and all the client-dbus tests passed, but then the the Jenkins stratisd test failed anyway due to some error I've never seen before having to do w/ cross-compilation. @trgill could you take a look at the stratisd Jenkins test?

**Comment by trgill** [comment]
looking now...

**Comment by mulkieran** [comment]
@trgill I think the cli-with-stratisd test may be having the same problem, which has to do with rustup, AFAICT. But that's all I know.

**Comment by trgill** [comment]
@mulkieran the problem was due to a mistake I made updating the Jenkins jobs.  Sorry for the trouble.  (due to adding rustup default 1.26.0)

There is still a problem in the cli-with-stratisd - but after re-submitting the job - it looks like a python issue.

**Comment by agrover** [comment]
please fix this as soon as you can.

**Comment by mulkieran** [comment]
I think that the problem is that the stratis-cli tests are too old for the version of dbus-client-gen that is available. dbus-client-gen must be the newest release, just judging by the errors. The tests can't be pulling from the stratis-cli master, or they would be working correctly with the new dbus-client-gen release. Perhaps the tests are being pulled from the most recent stratis-cli release.

I _think_ that if the stratis-cli tests were being pulled from the master branch, they should work.

I do not know if there is a stable solution to the problem of where to pull the stratis-cli tests from for these stratisd tests.
We should probably go ahead and use master now.

**Comment by trgill** [comment]
The problem was in the Jenkins script.  It is now pulling master for stratis-cli.

**Comment by mulkieran** [comment]
I will go ahead and restart and see what happens.

**Pull request merged**
