### PR TITLE
Collect all errors on failure to read BDA in read_bda

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
If I corrupt the first BDA signature block, at sector 1 of the device, I see this error:
```
[2021-04-12T21:41:50Z WARN  libstratis::engine::strat_engine::liminal::identify] udev identified device /dev/vdb1 as a Stratis device but encountered an error while reading Stratis header for device /dev/vdb1: IO error: Bad file descriptor (os error 9), disregarding the device
```

...and the pool does not start.  However, blkid and udev are able to detect the stratis header, while stratisd itself isn't.

So it seems that, in order for the pool to be launchable, both BDA signature blocks need to be intact.  Once I "restore" the one that's corrupt, stratisd "finds" it and launches the pool:
```
[2021-04-12T21:52:50Z DEBUG libstratis::engine::strat_engine::liminal::identify] Stratis block device with Stratis device description: Stratis pool UUID: "56e54929-2b37-4dc6-a801-9b5d69e2decf", Stratis device UUID: "7a9972e4-5ae0-47ad-9abf-7fbd48f1fc1c", device number: "252:17", devnode: "/dev/vdb1" identified
[2021-04-12T21:52:50Z INFO  libstratis::engine::strat_engine::liminal::device_info] Device information Stratis device description: Stratis pool UUID: "56e54929-2b37-4dc6-a801-9b5d69e2decf", Stratis device UUID: "7a9972e4-5ae0-47ad-9abf-7fbd48f1fc1c", device number: "252:17", devnode: "/dev/vdb1" discovered and inserted into the set for its pool UUID
```

**Comment by mulkieran** [comment]
@bgurney-rh The first error, "Bad file descriptor" is odd. stratisd should be able to proceed with just the one sigblock, it seems like it must have hit some other error. That it comes up eventually once the sig block is restored is good. Did you have to take any other action

@bgurney-rh What happens when you corrupt two MDA headers?

**Comment by bgurney-rh** [comment]
This is what happens if I corrupt both MDA headers:
```
[2021-04-13T14:09:17Z WARN  libstratis::engine::strat_engine::metadata::mda] First MDA header is invalid: Engine error: MDA region header CRC
[2021-04-13T14:09:17Z INFO  libstratis::engine::strat_engine::liminal::liminal] Attempt to set up pool failed, but it may be possible to set up the pool later, if the situation changes: There was an error encountered when reading the BDAs for the devices found for pool with UUID 73ebc693-16c1-487f-b371-a0c72cee72dd: Error: Failed to read BDA from device Stratis pool UUID: "73ebc693-16c1-487f-b371-a0c72cee72dd", Stratis device UUID: "f0723d70-5a2d-4203-9964-8ad4e57f8618", device number: "252:17", devnode: "/dev/vdb1": Engine error: MDA region header CRC
```

**Comment by bgurney-rh** [comment]
For the case where one BDA signature block was corrupted, after I "backed up" the good signature block, and "restored" its contents to the corrupted location, stratisd detected it, and immediately launched the pool.  (Which is a little frightening, as perhaps I don't want to launch it yet.)

**Comment by mulkieran** [comment]
> This is what happens if I corrupt both MDA headers:
> 
> ```
> [2021-04-13T14:09:17Z WARN  libstratis::engine::strat_engine::metadata::mda] First MDA header is invalid: Engine error: MDA region header CRC
> [2021-04-13T14:09:17Z INFO  libstratis::engine::strat_engine::liminal::liminal] Attempt to set up pool failed, but it may be possible to set up the pool later, if the situation changes: There was an error encountered when reading the BDAs for the devices found for pool with UUID 73ebc693-16c1-487f-b371-a0c72cee72dd: Error: Failed to read BDA from device Stratis pool UUID: "73ebc693-16c1-487f-b371-a0c72cee72dd", Stratis device UUID: "f0723d70-5a2d-4203-9964-8ad4e57f8618", device number: "252:17", devnode: "/dev/vdb1": Engine error: MDA region header CRC
> ```
> 
> If the devices aren't already mapped, then they fail to map, because the MDA headers can't be read, in order to find the information to create the device stack for the pool.

The error message looks much improved, as it now clearly identifies _which device_ has the corrupted metadata header.

**Comment by mulkieran** [comment]
> For the case where one BDA signature block was corrupted, after I "backed up" the good signature block, and "restored" its contents to the corrupted location, stratisd detected it, and immediately launched the pool. (Which is a little frightening, as perhaps I don't want to launch it yet.)

The device discovery launches all the things as soon as they are ready. stratisd simply isn't cognizant of what was going on previously. The udev event comes in, it reads the data, combines it w/ the existing information about devices, here it supercedes the old info with the new, and brings the pool right up.

**Review by bgurney-rh — APPROVED** [review]

**Comment by mulkieran** [comment]
Re running stratisd-nonrust, it's stuck on test_unique.

**Pull request merged**
