### PR TITLE
Remove dbus enums

### LINKED ISSUE #1167: Remove bad DbusErrorEnum enums such as NIX_ERROR
We haven't looked at DbusErrorEnum and I think it is showing its age. For example:

* NIX_ERROR: we probably shouldn't expose the crate source of an error. Why should API users depend on this?
* INTERNAL_ERROR: How is this different from ERROR? It just sounds scarier (to me). See #1160. System-breaking errors should also consider putting the pool into an error state (#1121)
* IO_ERROR: Why would API users differentiate between this and ERROR?

I like the other ones -- API users may programmatically want to check if an API call failed for reasons like BUSY, ALREADY_EXISTS, or NOTFOUND, and then do a fallback action for example, but the ones above we should consider removing before API freeze for Stratis 1.0.

### PR DESCRIPTION
**Pull request by agrover**
fixes #1167

### CODE REVIEW

**Comment by agrover** [comment]
The requirement I've been considering for these enums is: are different values something that a client could use to do something useful? e.g. a client may need a given filesystem to exist. The race-free way to ensure this is to try and create it and then continue if it gets ALREADY_EXISTS. (i.e. it's a Stratis error, but it's not really an error to the client) Any other error would cause the client to stop what it was doing.

Can you think of any case where a client would treat an INTERNAL_ERROR differently then an ERROR?

**Comment by mulkieran** [comment]
If _I_ say an internal error I would probably consider trying to bring stratisd down and then start it up again. If I saw a not internal error I would try to poke around in the environment, see what caused the problem. An automatic monitoring or reporting tool might do something similar.

**Comment by agrover** [comment]
So you are ok with never currently returning INTERNAL_ERROR, but just keep it around as documented valid return value for possible future use?

**Comment by agrover** [comment]
Ok, I misread what you said above. You said:

> Getting rid of D-Bus IO and NIX_ERRORs and throwing most of the engine errors into D-Bus ERROR and none of them into D-Bus INTERNAL_ERROR is the part that seems right to me.

So what would be left to return INTERNAL_ERROR? If we tried to lookup a device that we were exporting a dbus object for and it wasn't there, i.e. things that should never happen?

**Comment by mulkieran** [comment]
Wherever ```INTERNAL_ERROR``` is explicitly decided on in the D-Bus layer, i.e., not decided on because mapped to from an engine error it should remain, as far as I can tell.   ```dbus_api/filesystem.rs```, ```dbus_api/macros.rs```, ```dbus_api/pool.rs``` shouldn't be changed.

**Comment by agrover** [comment]
OK, kept INTERNAL_ERROR and just mapped engine errors to ERROR.

**Pull request closed without merging**
