### PR TITLE
Remove rpassword dependency

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to #3337

### CODE REVIEW

**Comment by mulkieran** [comment]
conflict is just in imports

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
@jbaublitz Plz rebase when you get the chance.

**Review by bmr-cymru — APPROVED** [review]

**Comment by jbaublitz** [comment]
@mulkieran I want to make one last change before this gets merged.

**Comment by mulkieran** [comment]
@jbaublitz Ok. Waiting on your change.

**Comment by jbaublitz** [comment]
Okay ready again.

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
