### PR TITLE
Add crypt module and use for device initialization

### LINKED ISSUE #1822: Design an interface for the explicit part of reading and writing luks2 metadata
* You might as well call the new module something like "crypt.rs", and
I believe it should be a sibling of the "udev.rs" module.

* I believe that it should be testable using our standard infrastructure,
which supplies a bunch of devices to work with. You should be able to
write a bunch of tests that ensure that the appropriate token can be written
for a designated keyslot, and also read back out. If you can take the tests down
a level, and write them like we write our Stratis metadata tests, which don't require
an actual device, but rather just an open file descriptor, that would also be
nice, but I suspect that it is made impossible by the libcryptsetup interface.
Essentially, your tests should be able to encrypt a device completely, setting
a Stratis token in the selected keyslot, and then reopen the device by
locating the keyslot that Stratis indicates that it owns with the token,
opening the device, and reading some
data back out from the device. For these tests, you should not put Stratis
metadata on the device. Just put any kind of value that can't be easily
duplicated, this will be an easier and more direct way to do the test.

* From a device discovery point of view the following would be ideal. It should be
possible to, given a device identified as luks2, scan all keyslots for any token
which identifies the device as a Stratis device. It should return some collection
of results, rather than just a single result, in case there are more than one
keyslot which seems to belong to Stratis. For each keyslot identified as belonging
to Stratis it should return both the keyslot number and the token, either in
its original JSON form, or in some useful representation of that form.
You will find the serde crate, which we already make use of for our Stratis
variable length metadata, helpful here, most likely. For device discovery,
I think identifying the token and opening the device should be separate actions.

* For device initialization, it will be necessary to offer facilities to
write the token. Since reading tokens is inexpensive, Stratis does not need to have
a designated reserved keyslot, so you may want to design the
facility to write to the next open keyslot. You may want to combine writing the
token and setting the key into a single action, as you do not want one with out
the other.

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #1908 
Closes #1822

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran One question before we merge. Do we want to release a new version of libcryptsetup-rs first so we can fix Cargo.toml?

**Comment by mulkieran** [comment]
I missed the question!

**Comment by mulkieran** [comment]
@jbaublitz I think it would be better if you cut a new release of cryptsetup; it would make our Cargo.toml a little more standard and be a kind of checkpoint for the cryptsetup bindings.

**Comment by jbaublitz** [comment]
Travis is not responding. Is it sufficient to rely on Jenkins here or should I open a new PR?

**Pull request merged**
