### PR TITLE
Update all dependencies

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
It pulls in dependencies that are not supported by 1.31.0 compiler (which we must continue to support).

**Comment by ignatenkobrain** [comment]
@mulkieran omg... I'll set it to `>=0.8.0,<0.10` and downgrade in lockfile

**Comment by mulkieran** [comment]
This is motivated by packaging problems on Fedora, which I don't fully understand yet. Moving to July.

**Comment by cuviper** [comment]
Updating semver in `Cargo.toml` helps Fedora if we can get everything on the latest version, so we don't have to maintain multiple compat versions of crates. The broader version changes in `Cargo.lock` don't really matter for this though.

Tip: you can explicitly update just the changed deps with `cargo update -p rand -p proptest`. Specific versions of a crate can be chosen like `cargo update -p foo --precise 1.2.3` if you need to step back to a version compatible with 1.31 for the lock file.

**Comment by mulkieran** [comment]
I'll close this and get a fresh start on a less constrained approach, since we have raised our lowest supported compiler to 1.35.

**Pull request closed without merging**
