### PR TITLE
Only allow one filesystem to be created at a time.

### PR DESCRIPTION
**Pull request by trgill**
Signed-off-by: Todd Gill <tgill@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
This is a general comment: have we agreed in principle that these restrictions on operations will be implemented solely in stratisd, i.e., the CLI will not be touched?

**Comment by trgill** [comment]
Yes, that was my take on issue #763 

With this change the CLI has the following output: 

# stratis filesystem create p1 fs1 fs2
Execution failed: 5: creation of multiple filesystems currently not supported - create one filesystem at a time

I'm not finished - need to make sure the error code is correct. Also need to improve the wording.

**Comment by mulkieran** [comment]
Now that we have D-Bus tests in stratisd, probably a good idea to add a test there, as well.

**Comment by trgill** [comment]
@mulkieran any suggestions re: what to do with the tests that no longer pass?

I'm thinking I tag them to be skipped for now.  Re-working them to pass with a temporary change seems bad.

Agree?

**Comment by mulkieran** [comment]
@trgill Yes, skipping seems right to me.

**Comment by agrover** [comment]
lookin good. I set to review-final. Merge?

**Pull request merged**
