### PR TITLE
Rework disk scanning strategy in tests

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #1954

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran I can't believe I didn't think of this before! Moving back to in progress because we can use libcryptsetup-rs to check if it's busy as opposed to sleeping. We should definitely do this instead.

**Comment by mulkieran** [comment]
Ok!

**Comment by jbaublitz** [comment]
@mulkieran I'm going to leave this PR in progress until CI passes but it does pass locally on real devices so I'm going to wager a guess that this works. I was thinking about the problem incorrectly because I wanted to check if the physical device is busy where that's not necessarily the problem. We actually want to verify that the devicemapper crypt device is not busy which we can do easily through libcryptsetup-rs. This should make this test reliable and we should be able to keep it moving forward.

**Comment by jbaublitz** [comment]
Also removing the FIXME now.

**Comment by jbaublitz** [comment]
Ready for review.

**Pull request closed without merging**
