### PR TITLE
Remove unnecessary trait bounds from metadata module

### LINKED ISSUE #1869: Remove unnecessary trait bounds, especially Write, from methods in metadata module

### PR DESCRIPTION
**Pull request by lleshchi**
Resolves #1869

### CODE REVIEW

**Comment by lleshchi** [comment]
I checked the trait bounds for the other files in this module, and those seemed to be used appropriately.

**Comment by jbaublitz** [comment]
The test failure may be due to my testing leaving crypt devices around. It doesn't at all look related to this.

**Comment by mulkieran** [comment]
@jbaublitz Once all tests have passed, please go ahead and merge this one.

**Comment by jbaublitz** [comment]
Will do.

@bgurney-rh Let's chat today about rerunning this and cleaning up whatever may have gone wrong with Jenkins.

**Comment by bgurney-rh** [comment]
I restarted the stratisd test; it must have been one of multiple jobs that failed on a node that had a stale crypt volume left over.

**Comment by jbaublitz** [comment]
@bgurney-rh Thanks! I'm doing my local testing of my new tests before pushing to run on CI again.

**Pull request merged**
