### PR TITLE
Rewrite find_all()

### PR DESCRIPTION
**Pull request by mulkieran**
Rewrite ```find_all()``` and add a test of its correct operation.

### CODE REVIEW

**Comment by mulkieran** [comment]
A bunch of these commits are pulled from #302.

**Comment by mulkieran** [comment]
@agrover @trgill review? I think all non-test commits could probably be squashed into one if acked.

**Comment by agrover** [comment]
Please add a brief PR description.

Also, if `find_all` just returns Devices, where do we instantiate BlockDevs? Does that get re-added in a later PR?

**Comment by mulkieran** [comment]
We instantiate the BlockDevs in a subsequent step, when we have obtained more complete information.

**Comment by mulkieran** [comment]
rebased

**Pull request merged**
