### PR TITLE
Move cleanup code into a separate module

### PR DESCRIPTION
**Pull request by mulkieran**
There will be very much more as time goes on.

Use newly created wipe_blockdevs() method where appropriate.

Tidy up some cleanup code adding TODOs where appropriate.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review?

This is starting to block #408 .

Also, note the TODOs. These mark where we should be updating a hypothetical state machine, or, by some other means, communicating the problem in a programmatic way.

Note, however, that the TODOs are in very distinct locations, one in blockdevmgr and the other in pool. That means that any state machine we update must be global, or perhaps we need to enrich the return type of a lot of methods, or perhaps we actually need to be writing this information in some kind of file somewhere, or some combination thereof.

**Comment by mulkieran** [comment]
One option is to pass the state machine, owned by the engine as a mutable reference. That would be a helpful indication in the signature of the method of its effects.

**Comment by agrover** [comment]
👍 for this PR without the environment state commit, based on our discussion in team mtg.

**Comment by mulkieran** [comment]
rebased and whatnot.

**Pull request merged**
