### PR TITLE
No longer pin to lower rustfmt version

### PR DESCRIPTION
**Pull request by mulkieran**
The bug that we were triggering was fixed in the newest version.

https://github.com/rust-lang-nursery/rustfmt/issues/1280

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Giving this another try, since it has been a few weeks.

**Comment by mulkieran** [comment]
Let's go ahead. But I still wouldn't try to do any configuration, I expect anything but the defaults will still be funky:
https://github.com/rust-lang-nursery/rustfmt/issues/1507.

@agrover @trgill review?

**Comment by agrover** [comment]
I think I'd feel more comfortable if we kept the pin but just updated to the newer version. It still seems prudent to evaluate changes before adopting them. This keeps us all in sync with each other and helps avoid lost productivity if some version starts breaking.

**Comment by mulkieran** [comment]
I think the process could work like this...don't pin the version. If a PR fails due to rustfmt doing something dumb, pin to the previous version and wait until rustfmt gets better again. Otherwise, the coordination overhead is actually higher and the CI doesn't help us as much as it should.

**Comment by agrover** [comment]
OK, if you think this is best.

**Pull request merged**
