### PR TITLE
Pay attention to pre-existing stratisd process in SimTestCase

### PR DESCRIPTION
**Pull request by mulkieran**
Related: https://github.com/stratis-storage/project/issues/54, https://github.com/stratis-storage/project/issues/53.

### CODE REVIEW

**Comment by mulkieran** [comment]
It looks like the changes are working just great, but that there is an existing stratisd process on the stratisd-nonrust machine.

**Comment by bgurney-rh** [comment]
I just terminated the existing "target/debug/stratisd --sim" process, and re-ran the stratisd-nonrust test; it looks like it succeeded.

**Comment by mulkieran** [comment]
Ok! For people who want to see what the output looks like if there is a pre-existing stratisd job, check out the previous non-rust Jenkins failure.

**Comment by bgurney-rh** [comment]
Here's a sample of the output:
```
E       AssertionError: Evidently a stratisd process is already running.
```

**Pull request merged**
