### PR TITLE
Cargo.toml: add vendor-filter metadata

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#642

### CODE REVIEW

**Comment by bgurney-rh** [comment]
Amending `all-features = true` to ensure that pretty-hex is included

**Comment by mulkieran** [comment]
The ```*``` configuration works, but I encountered an error:

```
Gathering metadata for platforms
error: Executing cargo metadata: Error during execution of `cargo metadata`: error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target m68k-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: could not create LLVM TargetMachine for triple: m68k-unknown-linux-gnu: No available targets are compatible with triple "m68k-unknown-linux-gnu"
```

**Review by mulkieran — CHANGES_REQUESTED** [review]
Add tier = "2" so this will build with Fedora Rust release, and we can consider this ready to merge.

**Comment by bgurney-rh** [comment]
Amended `tier = "2"`

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
