### PR TITLE
Preliminary work on encryption

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #1771

### CODE REVIEW

**Comment by mulkieran** [comment]
Some beta lints are failing...

**Comment by jbaublitz** [comment]
See #1811 for an explanation of why CI is failing.

**Comment by mulkieran** [comment]
@jbaublitz Please rebase again, for conflicts.

**Comment by mulkieran** [comment]
Feel free to close this PR and open a new one with all commits squashed into one in order to make rebasing easier.

**Pull request closed without merging**
