### PR TITLE
stratis_dbusquery_version: add Apache v2.0 license header

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by mulkieran** [comment]
It's possible this should be Apache, like the udev script. Let's check in standup.

**Comment by jbaublitz** [comment]
I chose Apache because it's simply a client of our MPLv2 code and I felt that opening it up for even more general use made sense here. I'm happy to discuss this at stand up and explain my reasoning. Either way, I think the licenses in these two scripts should be consistent with each other even if they're not consistent with stratisd.

**Comment by mulkieran** [comment]
> I chose Apache because it's simply a client of our MPLv2 code and I felt that opening it up for even more general use made sense here. I'm happy to discuss this at stand up and explain my reasoning. Either way, I think the licenses in these two scripts should be consistent with each other even if they're not consistent with stratisd.

I agree w/ consistency criterion. Let's talk in standup.

**Comment by bgurney-rh** [comment]
I just force-pushed a commit to change to an Apache v2.0 license header, as discussed in standup.

**Comment by mulkieran** [comment]
@bgurney-rh: Need to rebase one more time.

**Comment by bgurney-rh** [comment]
Rebased.

**Comment by mulkieran** [comment]
@bgurney-rh Please rebase.

**Comment by bgurney-rh** [comment]
Rebased.

**Pull request merged**
