### PR TITLE
Ensure that rename_filesystem writes out filesystem metadata

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #456.

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Test failed, good.

**Comment by mulkieran** [comment]
Test failed again, bad.

**Comment by mulkieran** [comment]
Test was broken, whoops.

**Comment by mulkieran** [comment]
This is now blocked by #471.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Tests now pass, due to changes pulled in from master.

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by mulkieran** [comment]
I can call the methods ```rename_*_pre```.

**Comment by mulkieran** [comment]
Done.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
👍 thanks, merging

**Pull request merged**
