### PR TITLE
Log if error when wiping just initialized block devices

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Review by jbaublitz — COMMENTED** [review]
Would it be reasonable to return a `NoActionRollback` error variant here containing the original error and the rollback error but not setting an `ActionAvailability` level?

**Comment by mulkieran** [comment]
@jbaublitz Ok, I think this is ready again.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
unusual error; bears investigation.

**Comment by mulkieran** [comment]
rebased

**Pull request merged**
