### PR TITLE
Move engine state report to Manager.r4 interface

### LINKED ISSUE #2369: Migrate engine state report functionality to manager interface
* Add a method to the Manager interface called, say, "EngineStateReport".
* Drop the support for the corresponding key in the Report interface.

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2369 
Supercedes #2371

### CODE REVIEW

**Comment by mulkieran** [comment]
Looks good. Holding in pending while CLI development is completed.

**Comment by jbaublitz** [comment]
@mulkieran I left out the `Cargo.lock` update in the bump commit so that's forced pushed in now.

**Comment by mulkieran** [comment]
ok, thx!

**Comment by jbaublitz** [comment]
@mulkieran @lleshchi brought up the fact that we should whitelist the `EngineStateReport` method in `stratisd.conf`.

**Comment by mulkieran** [comment]
Yes! Please go ahead and do that.

**Comment by jbaublitz** [comment]
@mulkieran Okay this is now incorporated into the first commit.

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
@jbaublitz Please do one last rebase and this should be good to go.

**Comment by jbaublitz** [comment]
Rebased

**Pull request merged**
