### PR TITLE
The cache part of the cache tier work

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #631.

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased to bring in clippy update. There is no obvious reason reason for stratisd-dbus-client test failures: https://stratis-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/stratisd-client-dbus-tests/194/.

**Comment by mulkieran** [comment]
It is expected that some of the stratisd-dbus-client tests will fail. This is because the method ```AddDevs``` has been renamed to ```AddBlockDevs```. I'll open a PR to demonstrate how that would be fixed up in a bit.

**Comment by mulkieran** [comment]
@agrover review, please?

**Comment by agrover** [comment]
It's better to think of cache devices being in a separate "Tier" rather than a different "Role" from data blockdevs. Let's save the word "role" for differentiating blockdevs within the same tier, (although this is theoretical as we don't do this differentiation yet, but an example of we might add some day is "raid spare" -- a blockdev requiring different treatment than the others, but within the same collection of blockdevs, the same tier.)

I think the semantics we want are that blockdevs in a tier can change roles in situ, but can only change tiers by being removed and re-added.

The above is probably more relevant to future PR work but I just wanted to share my thinking before changing the design doc. In this PR we're heading down the road to blockdevs from different tiers (and roles) exporting identical APIs -- the same set of properties and methods. I just want to confirm that that's the approach we want to take.

**Comment by mulkieran** [comment]
rebased. Updated D-Bus tests. Expected to pass.

**Comment by mulkieran** [comment]
It passed. We currently have no AddCacheDevs tests...

**Comment by mulkieran** [comment]
Tests expected to pass.

**Comment by mulkieran** [comment]
This is rebased off nix branch so that it can compile against devicemapper master.

**Comment by mulkieran** [comment]
Just a helpful clippy error that time.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by mulkieran** [comment]
There is no reason why cachedev's can't use the identical metadata layout as datadevs. Therefore, we can reuse our metadata module and just worry about the variable length metadata. Furthermore, I see no reason why any variable length metadata needs to be stored on the cachedevs. It makes just as much sense to store all information about cachedevs that is necessary to be stored in the variable length metadata that is written to the datadevs. And the metadata about the cachedevs need not be so ornate, since there isn't a complicated mapping from the upper layer to the devs. There is some info to store, though.

**Comment by mulkieran** [comment]
clippy, a fix should be available soon.

**Comment by mulkieran** [comment]
Jenkins failure is unusual: ": Some(Error { repr: Os { code: 84, message: "Invalid or incomplete multibyte or wide character" } "

**Comment by agrover** [comment]
> There is no reason why cachedev's can't use the identical metadata layout as datadevs. Therefore, we can reuse our metadata module and just worry about the variable length metadata. Furthermore, I see no reason why any variable length metadata needs to be stored on the cachedevs. It makes just as much sense to store all information about cachedevs that is necessary to be stored in the variable length metadata that is written to the datadevs. And the metadata about the cachedevs need not be so ornate, since there isn't a complicated mapping from the upper layer to the devs. There is some info to store, though.

OK, sounds good.

**Comment by mulkieran** [comment]
Fix some more clippy errors and examine a real bug. When setting up the Cache Device, its length doesn't match previous cache device. There are other problems, like that the device number doesn't match previous device number, but I think the error there is that we should not be checking the device number in the first place.

**Comment by mulkieran** [comment]
Yay, devicemapper bug fix means test passes.

**Comment by mulkieran** [comment]
Extending tests to check the cache status. More sanity, really.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Jenkins tests failing no space left on device...seems unlikely.

**Comment by mulkieran** [comment]
Did a soft reboot of fedora-server-1 to hopefully clear out Jenkins failures.

**Comment by mulkieran** [comment]
build and docs Travis tests were stuck for some reason, everything else had passed.

**Comment by mulkieran** [comment]
Hard reboot. Jenkins errors remain the same.

**Comment by mulkieran** [comment]
Travis is doing fine, other than a clippy test that can't start.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Superceded by #811.

**Pull request closed without merging**
