### PR TITLE
Move up to newer version of rustfmt

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
This, and the corresponding devicemapper PR are somewhat important to my workflow, as I will have to make some adjustments on my newly upgraded machine in order to use the older version of rustfmt, whereas if this is accepted, I won't have to spend time making those adjustments.

**Comment by agrover** [comment]
I'm also using the newer rustfmt and so this would make my life easier. I've opened #1053 because that seems longer-term like a better solution.

**Comment by mulkieran** [comment]
rebased one last time, very few changes.

**Comment by mulkieran** [comment]
A Jenkins test fails because a thin device is busy when tearing down a pool. This is interesting, but obviously irrelevant to these changes. So, I'm going to merge this, and investigate the error somewhat more afterwards.

**Pull request merged**
