### PR TITLE
Adjust some Python package version

### PR DESCRIPTION
**Pull request by mulkieran**
Separate stratisd scripts into developer tools and code maintenance tools. Code maintenance tools only need to be runnable in the current recommended development environment and are _never_ released.

### CODE REVIEW

**Comment by mulkieran** [comment]
Only allowed failures failing...

**Review by drckeefe — APPROVED** [review]

**Comment by mulkieran** [comment]
looks like an accidental stratisd test error, also.

**Comment by mulkieran** [comment]
I realized that the previous quick fix was a bit too quick. The new fix is a bit more comprehensive, so I'm asking for review from everybody.

**Comment by mulkieran** [comment]
Whoops, yet another change I ought to make coming up.

**Review by drckeefe — APPROVED** [review]

**Comment by mulkieran** [comment]
Nah, change planned was to get rid of some deprecation warnings in update_cargo_crates.py, but that looks a little tricky, so putting this up as is.

**Review by drckeefe — APPROVED** [review]

**Review by bgurney-rh — APPROVED** [review]

**Comment by mulkieran** [comment]
Whoops, I meant to close this and open a final, which is why it's a little messy. As it happens, it's only a change to our code maintenance scripts, so no big deal, but still a mistake.

**Pull request merged**
