### PR TITLE
Clarify how to allocate all available space on a blockdev

### PR DESCRIPTION
**Pull request by mulkieran**
Use None to mean give everything.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
Cherry-picked from #722. Somewhat related, but not so closely that it can't be considered somewhat on its own merits.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
Using `None` to mean "all" feels weird. How about adding another fn called `request_all_space`?

**Comment by mulkieran** [comment]
@agrover Here is the less code approach, will that work?

**Comment by agrover** [comment]
Yes, composing available() and request() seems nice.

**Comment by mulkieran** [comment]
Doesn't change any actual code, seems approved, merged.

**Pull request merged**
