### PR TITLE
Update stratisd to clap 3.1.18

### PR DESCRIPTION
**Pull request by bmr-cymru**
Update stratisd to use Clap v3

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Rebased

**Comment by bmr-cymru** [comment]
Rebased and tidied up the branch.

**Comment by bmr-cymru** [comment]
`udevadm settle` exiting with status 1 on Ubuntu?

**Review by mulkieran — APPROVED** [review]

**Review by jbaublitz — APPROVED** [review]

**Comment by bmr-cymru** [comment]
Rebased

**Pull request merged**
