### PR TITLE
Fix for thin provisioning rework in boot work

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to #2854

I've tested this and verified it resolves the issue.

### CODE REVIEW

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
fedora repos are funky; might as well ignore those failures.

**Comment by bmr-cymru** [comment]
The patch looks completely correct, but I wanted to pull this branch onto my Stratis rootfs test system and try out some tests there. I've had to bump up my VM's memory allocation to get the current branches building reliably - that's finished now but I'm still seeing a boot failure with the current start-stop branch including this change. I'm just waiting for the dracut timeouts to expire so that I can try to debug it. I'll update the PR again when I have a better idea what's going on.

This did prompt me to take another look at #2830 and in particular the commit that introduces `thin_metadata_size`:

```
commit 0d1d50972cc8e5869e7154294455640c1877e358
Author: John Baublitz <jbaublitz@redhat.com>
Date:   Wed Nov 3 16:36:42 2021 -0400

    Transition from greedy to lazy allocation
    
    This commit adds a few notable changes. One is a transition to lazy
    allocation with migration code to ensure that older versions of stratisd
    still function properly after migration. Another is a filesystem limit
    to allow precise calculation of the necessary metadata space for the
    thin pool. This ensures that a user can never run out of metadata space
    as the amount required is calculated and allocated upfront.
```

My only concern here is the naming - thin-provisioning-tools has long used `thin_` as the prefix for the thinp tools that it provides, and I wonder if this might have the potential to cause some confusion? It could also lead to conflicts if thin-provisioning-tools ever introduced a similarly named command (there is already `thin_metadata_pack` and `thin_metadata_unpack`.

**Comment by bmr-cymru** [comment]
Ah never mind - I had mis-read the commit that I mentioned, and I thought that `thin_metadata_size` was being provided by stratisd. I can see now that it's just invoking the tool supplied by thin-provisioning-tools, which is absolutely fine!

**Review by bmr-cymru — APPROVED** [review]
Tested on an F35 Stratis root fs system and I can successfully boot with this patch included in the start-stop branch.

**Pull request merged**
