### PR TITLE
Reorder tests so that misc_tests run after udev_tests

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Review by bgurney-rh — APPROVED** [review]

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@bgurney-rh Looks like stratis-tester-8 has an extra /dev/vdb device.

**Comment by mulkieran** [comment]
@bgurney-rh Re-requesting review. I put up an additional commit.

**Comment by bgurney-rh** [comment]
> @bgurney-rh Looks like stratis-tester-8 has an extra /dev/vdb device.

I found a stale crypto_LUKS header on that test device.  It's cleared now.

**Review by bgurney-rh — APPROVED** [review]

**Pull request merged**
