### PR TITLE
Add some project infrastructure

### PR DESCRIPTION
**Pull request by mulkieran**
Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review?

This only runs "cargo fmt" which means it only detects formatting and syntax errors.
My plan was to run "cargo build" as well, so, even though we weren't testing we could at least make sure that we hadn't accidentally committed any compiler errors. But "cargo build" has problems installing dbus-rs: https://travis-ci.org/stratis-storage/stratisd/builds/174912560. I'll see whether I can make further progress, but this PR should be somewhat useful for now.

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by trgill** [comment]
:+1:  Ok

**Comment by agrover** [comment]
:+1:

**Pull request merged**
