### PR TITLE
Set bindgen dependency to 0.63.0

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#551

### CODE REVIEW

**Comment by mulkieran** [comment]
@bgurney-rh In the same commit, set regex version requirement to 1.5.0. That should satisfy the requirements of bindgen, but be lower than the highest available on Fedora.

**Comment by bgurney-rh** [comment]
Amended previous commit to add regex version set to 1.5.0.

**Comment by bgurney-rh** [comment]
Trying again, with regex 1.5.4.

**Comment by bgurney-rh** [comment]
Looks good.  Updating Cargo.lock via another amended commit.

**Comment by bgurney-rh** [comment]
Rebased.

**Comment by mulkieran** [comment]
Annoying udevadm failures.

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
