### PR TITLE
Remove use of UUID references where possible.

### LINKED ISSUE #569: Uuid is Copy...we pass it around as a reference far too much

### PR DESCRIPTION
**Pull request by trgill**
Uuid implements Copy.  We shouldn't be passing it around as a reference.  

Resolves #569

Signed-off-by: Todd Gill <tgill@redhat.com>

### CODE REVIEW

**Comment by trgill** [comment]
@mulkieran what do you think?

**Comment by mulkieran** [comment]
It resolves #569, you can put that in the commit message.

**Comment by agrover** [comment]
BTW if commitmsg says "resolves #569" instead of "resolves issue #569" it will automatically close the issue when the PR is merged, see https://help.github.com/articles/closing-issues-using-keywords/

**Comment by trgill** [comment]
@agrover thanks

**Comment by mulkieran** [comment]
Merging, as last reviewer.

**Pull request merged**
