### PR TITLE
Remove memory mapped keyfile workaround

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes https://github.com/stratis-storage/project/issues/212

This PR is blocked on rebuilds of the Clevis packages in Fedora 37.

### CODE REVIEW

**Comment by mulkieran** [comment]
@jbaublitz It looks to me, from reading the CI logs, that the versions of clevis and cryptsetup that we require are both being installed properly. Something else may be causing the test failures.

**Comment by jbaublitz** [comment]
@mulkieran Take a look at the email I sent. It outlines in more detail why this is occurring. The basic idea is that the cryptsetup version is determined at compile time as opposed to dynamically and these packages were build before 2.6.1 was released in Fedora 37.

**Comment by mulkieran** [comment]
@jbaublitz Ah-hah. Ok, we'll hold it in Pending now and wait for Clevis to be rebuilt.

**Comment by jbaublitz** [comment]
@mulkieran @bmr-cymru Looks like the rebuilt packages have made their way into Fedora 37 so we're good to go!

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
May want to allow one more release of stratisd before this goes in.

**Pull request merged**
