### PR TITLE
Initialize MDAHeaders with correct CRC

### PR DESCRIPTION
**Pull request by mulkieran**
These patches are components of a bug fix from #476. They add a new test which explicitly tests the bug fix and a bit more documentation.

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover review?

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by agrover** [comment]
👍 , thanks

**Comment by mulkieran** [comment]
rebased, that's all.

**Comment by mulkieran** [comment]
Ok, merging.

**Pull request merged**
