### PR TITLE
Move engine state report to Manager.r4 interface

### LINKED ISSUE #2369: Migrate engine state report functionality to manager interface
* Add a method to the Manager interface called, say, "EngineStateReport".
* Drop the support for the corresponding key in the Report interface.

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2369

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks good! Need to bump manager interface spec in tests/client-dbus/src/stratisd_client_dbus/_data.py, but otherwise this seems good to go.

**Comment by jbaublitz** [comment]
Whoops! Resolved.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Whoops requires some test code updates also.

**Comment by jbaublitz** [comment]
I think this is resolved now. It looks like nonrust tests passed.

**Comment by mulkieran** [comment]
Looks good! Putting it in "Pending" while we decide precisely how to do CLI.

**Comment by mulkieran** [comment]
We'll want to queue up the CLI changes before we merge this, to avoid blackbox failures.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Please close this and open a new PR for final review. Please add to that PR a version bump for stratisd, to 2.4.0. That will allow the Python side of this change to require the new stratisd version.

**Pull request closed without merging**
