### PR TITLE
Omit long help

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Review by bmr-cymru — APPROVED** [review]

**Comment by mulkieran** [comment]
udevadm failures in tests...

**Review by jbaublitz — APPROVED** [review]
I tested both master and this PR and it appears the output is identical even without this code.

**Comment by mulkieran** [comment]
> The `if args.is_present("-h")` block also fairs badly with clap-3.1.18:
> 
> ```
> # RUST_BACKTRACE=1 target/debug/stratisd-min
> thread 'main' panicked at '`-h` is not a name of an argument or a group.
> Make sure you're using the name of the argument itself and not the name of short or long flags.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:659:14
> stack backtrace:
>    0: rust_begin_unwind
>    1: core::panicking::panic_fmt
>    2: clap::parse::matches::arg_matches::ArgMatches::get_arg
>              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:1144:17
>    3: clap::parse::matches::arg_matches::ArgMatches::is_present
>              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.1.18/src/parse/matches/arg_matches.rs:659:9
>    4: stratisd_min::main
>              at ./src/bin/stratis-min/stratisd-min.rs:139:8
>    5: core::ops::function::FnOnce::call_once
>              at /builddir/build/BUILD/rustc-1.60.0-src/library/core/src/ops/function.rs:227:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```
> 
> Switching to the argument name ("help") resolves this but it will end up disappearing anyway once this PR is merged.

Ok. This is in pending because it conflicts w/ https://github.com/stratis-storage/stratisd/pull/2999, but I'll merge it immediately after #2999 goes in.

**Comment by bmr-cymru** [comment]
I'll rebase the clap v3 branch once #2999 is merged and drop those changes.

**Comment by mulkieran** [comment]
rebased, conflicts resolved.

**Pull request merged**
