### PR TITLE
Master setup

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
expected to fail.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover: What happens if the actual size of the block device is different from the size recorded in the BDA? Will it be necessary to overwrite the BDA or at least the size value at some point?

Should we have chosen the other option, to store the size in the metadata, and not in the BDA?

**Comment by agrover** [comment]
Here's what my thinking is:
```
If bda.size > actual size // what? disk shrank!
    emit warning
    don't use disk (possibly causing pool to be unusable)

if bda.size < actual size // more space than expected
    Just use space up to bda.size
    possibly have some command to tell Stratis it can expand

if bda.size == actual size // we're good
    use the disk
```

**Comment by mulkieran** [comment]
Superceded by #370, #371.

**Pull request closed without merging**
