### PR TITLE
Avoid unwrap() in get_dm() method

### PR DESCRIPTION
**Pull request by mulkieran**
It seemed that it was necessary to hav an unwrap() in get_dm() because it
seemed that it was necessary to have get_dm() return a simple type, i.e.,
one without an Option or Result. The problem with this approach is that
it required the use of catch_unwind() at the point that get_dm() was
first called, to ensure an orderly exit.

This solution is exactly equivalent, but leaves out the unwind() and
hence the requirement to use catch_unwrap().

It changes get_dm() so that it returns a StratisResult, and it uses
the macro get_dm in every case where get_dm() is expected to succeed.

The solution is semantically equivalent to the previous approach; under
all circumstances it should behave in an equivalent manner.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
This is related to #974. Is it desirable to use a virtually identical method to locate external binaries?

**Comment by agrover** [comment]
Do we need the macro?

So with this PR we'd have `get_dm()`, used during init, and `get_dm!()`, used all the other times. Could this be `get_dm_init()` used during init, and then `get_dm()` used all the other times?

**Comment by mulkieran** [comment]
Macro-less version.

**Comment by mulkieran** [comment]
Now with comment fix!

**Comment by mulkieran** [comment]
I've answered the only request, so I'm calling it review final.

**Comment by agrover** [comment]
👍

**Pull request merged**
