### PR TITLE
Added help text to error message when a device is already in use

### PR DESCRIPTION
**Pull request by carzacc**
Addresses https://github.com/stratis-storage/stratis-cli/issues/208 along with https://github.com/stratis-storage/stratis-cli/pull/211

### CODE REVIEW

**Comment by agrover** [comment]
Hmm. I think we've had stratisd report errors, but stratis-cli catch them and make helpful suggestions like this one. Should (and could) something like this go in stratis-cli, @mulkieran ?

**Comment by mulkieran** [comment]
Related: https://github.com/stratis-storage/stratis-cli/pull/223.

**Comment by mulkieran** [comment]
It has just occurred to me that maybe it wouldn't be wrong to enrich the message so that it returns more stuff. We could use a D-Bus dictionary to stash various components, i.e., the "message", the backtrace, or whatever is desired. This way, we do offer more information to the CLI. I don't know if the CLI would necessarily be able to make much use of the backtrace, though, if it was formatted as text. Anyway, I think any further discussion of this should probably be in a separate issue.

**Comment by mulkieran** [comment]
I opened an issue about stratis-cli: https://github.com/stratis-storage/stratis-cli/issues/224.

**Comment by mulkieran** [comment]
We shouldn't really do this, but I've added another issue: #1421 about better error reporting from the engine.

**Pull request closed without merging**
