### PR TITLE
Fix two things in main method

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #1015

### CODE REVIEW

**Comment by agrover** [comment]
@mulkieran now that clippy is working again you should be able to see the issue in the travis tests. The warning doesn't seem very apt to me, but if there's a better alternative than silencing it, lemme know.

**Comment by mulkieran** [comment]
```
[root@localhost stratisd]# PYTHONPATH=./src ./target/x86_64-unknown-linux-gnu/debug/stratisd --sim --debug &
[2] 14700
Error: Daemon already running with pid: 14691
[2]+  Exit 1                  PYTHONPATH=./src ./target/x86_64-unknown-linux-gnu/debug/stratisd --sim --debug
```

**Comment by mulkieran** [comment]
This PR was augmented to fix a bug where the fix affects the exact same code as the clippy problem which it was originally designed to fix. I don't think there's much point in splitting them into two separate PRs since they are so close together and since the clippy fix would interfere with the bug fix.

**Comment by mulkieran** [comment]
Whoops. clippy found an extra ```.into()```. But I expect all will be fine now.

**Comment by agrover** [comment]
:+1:

**Pull request merged**
