### PR TITLE
Remove some stray publicity modifiers

### PR DESCRIPTION
**Pull request by mulkieran**
For better encapsulation.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
I might be taking this one back.

**Comment by mulkieran** [comment]
No, looks like its the right thing to do.

**Comment by mulkieran** [comment]
Oy, get rid of a single extra line that slipped in that rustfmt doesn't like.

**Comment by mulkieran** [comment]
This is _nearly_ trivial.

**Comment by agrover** [comment]
ok :+1:

**Comment by mulkieran** [comment]
That reordering was a mistake. It's totally backwards. I'll fix it.

**Comment by trgill** [comment]
:+1:

**Comment by mulkieran** [comment]
Something went wrong w/ Jenkins test. I'm just rebuilding and seeing if that clears it out. The problem is a failure in ```blockdevmgr::test_initialize```, to many pools were found.

**Comment by mulkieran** [comment]
Probably the machine needs a reboot?

**Comment by mulkieran** [comment]
I'm merging this thing as soon as last test passes.

**Pull request merged**
