### PR TITLE
Issue project 316

### PR DESCRIPTION
**Pull request by mulkieran**
Bumps stratisd version up to 3.0.0. Eliminates all stratis2 D-Bus APIs. Removes ConfigureSimulator D-Bus method entirely.
Leaves most methods that were in shared.rs for their respective interfaces where they were; these methods are likely to become shared on a subsequent minor release.

Defers any adjustment to FetchProperties keys.

Related https://github.com/stratis-storage/project/issues/316
Closes https://github.com/stratis-storage/project/issues/251

### CODE REVIEW

**Comment by mulkieran** [comment]
Some failures are expected. stratis-cli checks should succeed.

**Comment by mulkieran** [comment]
Next step. Can we clean out redundant FetchProperties keys?

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
Here we definitely should be able to eliminate the complexity associated with the init_cache/add_cachedevs change over.

**Comment by mulkieran** [comment]
Still in Draft, must not include temporary commit in final PR.

**Comment by mulkieran** [comment]
rebased.

**Review by jbaublitz — COMMENTED** [review]
This looks good so far!

**Pull request closed without merging**
