### PR TITLE
Add NO_TEST_CLEAN_UP env var to prevent test stack clean up

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to CI failures in #2949

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
The code looks fine. You'll want to document the environment variable in README_tests.md.

**Review by mulkieran — APPROVED** [review]

**Review by bmr-cymru — APPROVED** [review]
I have tested this with the clevis_loop_test_clevis_rebind_rollback test and it gives the expected behaviour allowing the stack to be preserved for debugging.

**Comment by mulkieran** [comment]
@jbaublitz Plz squash and I'll merge.

**Comment by jbaublitz** [comment]
Okay ready!

**Pull request merged**
