### PR TITLE
Add tests for FetchProperties

### LINKED ISSUE #1681: Run up some tests of our properties obtained by FetchProperties
We should definitely make sure of the types. Python is so forgiving, and the justbytes library is fairly forgiving, too, so the CLI tests are sometimes not going to pick up wrongly typed D-Bus values.

### PR DESCRIPTION
**Pull request by jbaublitz**
Supersedes #1694
Closes #1681

### CODE REVIEW

**Comment by bgurney-rh** [comment]
The previous TravisCI failure seemed to be due to some unrelated package issue on the instance it started for the clippy task, which passes now.

**Comment by jbaublitz** [comment]
Resolved and ready for review.

**Comment by jbaublitz** [comment]
It looks like that applies to all of the `FetchProperties` tests. I'll revise.

**Comment by jbaublitz** [comment]
I fixed up all of the properties tests (both `FetchProperties` and `GetManagedObjects` property tests). I'm going to search for an issue for the rest of the tests as there a great number of tests that don't follow this. I'll file a new one if it doesn't already exist.

**Comment by mulkieran** [comment]
> I fixed up all of the properties tests (both `FetchProperties` and `GetManagedObjects` property tests). I'm going to search for an issue for the rest of the tests as there a great number of tests that don't follow this. I'll file a new one if it doesn't already exist.

Please just fix up the test_fetch_properties files, i.e., the ones you're adding, and file an issue for all the rest.

I'm sure there are copy-paste errors galore, but I'ld like to keep this PR focussed on just your additions.

**Comment by jbaublitz** [comment]
`test_properties` changes reverted.

**Pull request closed without merging**
