### PR TITLE
Allow code generated by bindgen for testing struct layouts

### LINKED ISSUE #2658: In Rust 1.53 bindgen emits bindings that are rejected by the compiler
Sample error, they seem to be all the same:

```
error: dereferencing a null pointer
    --> /__w/stratisd/stratisd/target/debug/build/libstratis-2db48ea0cb163798/out/bindings.rs:3685:19
     |
3685 |         unsafe { &(*(::std::ptr::null::<__va_list_tag>())).reg_save_area as *const _ as usize },
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this code causes undefined behavior when executed
```

### PR DESCRIPTION
**Pull request by jbaublitz**
Closes #2658

### CODE REVIEW

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
This is good, just need to get #2657 in first.

**Comment by mulkieran** [comment]
@jbaublitz Ok, please rebase; I believe then I can merge it.

**Comment by jbaublitz** [comment]
@mulkieran Rebased.

**Comment by mulkieran** [comment]
thx! Actually, I have to put it in pending for now.

**Comment by mulkieran** [comment]
Thanks! I grabbed it and merged it in #2665 . I had forgotten that since it's a compiler error, not a clippy error, we'ld have to add an allow.

**Pull request closed without merging**
