### PR TITLE
Implement IntoIterator for BlockDevMgr and use it

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
First commit is cherry-picked from #383.

**Comment by agrover** [comment]
More code to do the same thing? Does the payoff come later?

**Comment by mulkieran** [comment]
I'm hoping someone can offer an explanation of the lifetime error.

**Comment by mulkieran** [comment]
@agrover Anything that can be done about the lifetime error I'm getting?

**Pull request closed without merging**
