### PR TITLE
Specify PathBuf type for blockdevs in parser

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Failures are due to Cockpit test error, looks like.

**Comment by martinpitt** [comment]
F40 passed, and the rawhide error is totally unrelated to stratis/cockpit:
```
+ systemctl start firewalld
+ firewall-cmd --add-service=cockpit --permanent
Error: [Errno 13] Permission denied: '/etc/firewalld/zones/public.xml'
```
That's almost surely some SELinux related regression. Please ignore. I'll try to reproduce this locally and report it.

**Comment by martinpitt** [comment]
See https://bodhi.fedoraproject.org/updates/FEDORA-2024-aa10dc94fe .  The automated tests are a sea of red.

**Review by jbaublitz — APPROVED** [review]

**Comment by mulkieran** [comment]
rebased

**Pull request merged**
