### PR TITLE
Add action info messages for pool creation, rename, and removal

### PR DESCRIPTION
**Pull request by bgurney-rh**
Supersedes: #1802

### CODE REVIEW

**Comment by mulkieran** [comment]
Just formatting errors...remember to run ```make fmt```.

**Comment by bgurney-rh** [comment]
Here's what the messages look like right now:
```
 INFO libstratis::engine::strat_engine::engine: pool created: uuid a1edb83f7c81494595864619b56196f7, name spool1
 INFO libstratis::engine::strat_engine::engine: pool renamed: uuid a1edb83f7c81494595864619b56196f7, old name spool1, new name spool2
 INFO libstratis::engine::strat_engine::engine: pool renamed: uuid a1edb83f7c81494595864619b56196f7, old name spool2, new name spool3
 INFO libstratis::engine::strat_engine::engine: pool renamed: uuid a1edb83f7c81494595864619b56196f7, old name spool3, new name spool1
 INFO libstratis::engine::strat_engine::engine: pool renamed: uuid a1edb83f7c81494595864619b56196f7, old name spool1, new name spool2
 INFO libstratis::engine::strat_engine::engine: pool renamed: uuid a1edb83f7c81494595864619b56196f7, old name spool2, new name spool3
 INFO libstratis::engine::strat_engine::engine: pool renamed: uuid a1edb83f7c81494595864619b56196f7, old name spool3, new name spool1
 INFO libstratis::engine::strat_engine::engine: pool destroyed: uuid a1edb83f7c81494595864619b56196f7, name spool1
```

**Comment by mulkieran** [comment]
@jbaublitz I think it would be better to always log, it would be more uniform. And I think logging "no action taken" at the info level is a reasonable choice.

When we talked in standup...the idea was to log as the method is entered, and also to log the outcome. I think this approach is probably the easiest to implement, and also the most useful to the reader of the log.

**Comment by jbaublitz** [comment]
Okay, sounds good. In that case I have some requested changes that I can bring up then.

**Comment by bgurney-rh** [comment]
This has been superseded by #1874

**Pull request closed without merging**
