### PR TITLE
Trgill create one filesystem

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by trgill** [comment]
Ok.  Thanks.

nth() takes a mutable self - to use it I need to make filesystems mutable.  I squashed the commit in the original PR.  (not sure that is the correct process here)

**Comment by agrover** [comment]
Please just use count. It's clearer and perf doesn't matter here.

**Comment by mulkieran** [comment]
@trgill ```nth()``` is starting to look scarier than ```count()```, because it requires mutable access on rustc 1.24.1 but not on 1.24.0 (my version). So, I'ld say go back to ```count()```.

**Comment by agrover** [comment]
parent PR merged, closing

**Pull request closed without merging**
