### PR TITLE
Some updates to real and loopbacked testing infrastructure

### PR DESCRIPTION
**Pull request by mulkieran**
Refactor real test infrastructure for simplicity and directness.

Make loop test infrastructure somewhat similar.

Resolves: #558.

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover @trgill review? This is obviously not the last word in testing infrastructure, but I think it's enough to be getting on with for now.

**Comment by agrover** [comment]
👍 from me

**Pull request merged**
