### PR TITLE
Have pool.check() return a Result

### PR DESCRIPTION
**Pull request by mulkieran**
Fixes a bug introduced in #537.

### CODE REVIEW

**Comment by mulkieran** [comment]
With this change, suddenly all tests succeed.

**Comment by mulkieran** [comment]
@agrover review?

**Comment by agrover** [comment]
Isn't this masking that the pool check didn't succeed? Do we know why the check is failing?

**Comment by mulkieran** [comment]
We have no evidence that the check was ever failing. ```<expr>.unwrap_or(error!("message"))``` prints "message" regardless of the value of ```<expr>```.

**Comment by agrover** [comment]
I am seeing that message intermittently.

**Comment by mulkieran** [comment]
It happens exactly when ```pool.check()``` runs and completes. So, if you're occasionally not seeing it, that must mean that pool.check() is not being run on occasion.

https://play.rust-lang.org/?gist=147aef4052459cdfd8a179c05025189c&version=stable

**Comment by mulkieran** [comment]
rebased.

**Comment by agrover** [comment]
oh yeah...`unwrap_or` always evaluates what's in the parens, I should've used `unwrap_or_else`!

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
