### PR TITLE
Improve a log message

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #1485.

### CODE REVIEW

**Comment by mulkieran** [comment]
This needs more work. free_space_check is intended to calculate the free space state for the whole data tier, but it ignores the number of blocks allocated to the metadata device entirely.

**Comment by mulkieran** [comment]
Supercedes #1491.

**Comment by mulkieran** [comment]
@bgurney-rh This is one for your investigation, if you want it.

**Comment by bgurney-rh** [comment]
After restarting the stratisd Jenkins test, the test passes.

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
