### PR TITLE
Relax fairness restriciton on AllOrSomeLock

### PR DESCRIPTION
**Pull request by jbaublitz**
Related to #3542

### CODE REVIEW

**Comment by jbaublitz** [comment]
You can disregard these failures. These are a bug that I introduced in this PR.

**Comment by jbaublitz** [comment]
I think they should be fixed now.

**Comment by jbaublitz** [comment]
@mulkieran The tests-with-testing-repo failure is actually interesting mainly because it indicates that our D-Bus signal code might have to be reworked if we accept this change because we will not longer be able to guarantee that the requests are processed in the order that they're received. The testing-farm failure is unexpected and I'm going to investigate further because it looks like the same problem.

**Comment by jbaublitz** [comment]
@mulkieran Looks like we're just waiting on Cockpit tests and I expect those to pass.

**Review by mulkieran — CHANGES_REQUESTED** [review]

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
