### PR TITLE
cleanup: remove unused file - rename StratisPool to Pool

### PR DESCRIPTION
**Pull request by trgill**
removed pool.rs and util.rs (currently not used)
move trait StratisPool to engine.rs
rename trait StratisPool to Pool

### CODE REVIEW

**Comment by trgill** [comment]
@mulkieran  @agrover  review?

**Comment by agrover** [comment]
actual commit content looks good, but there's a git issue. The PR should not have a merge commit in it, or list commit ac820aa. You might want to try rebasing the three commits on top of the current head (which includes ac820aa) and then doing a git push --force to this branch.

**Comment by trgill** [comment]
Ok - I addressed the git issue.   Sorry for the mistake.

**Comment by agrover** [comment]
ok, :+1: , thanks!

**Pull request merged**
