### PR TITLE
Fix MDARegions::older.

### PR DESCRIPTION
**Pull request by mulkieran**
It was reversed.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
@agrover @trgill review? This should be an easy ack. I noticed it when I noticed that the newer timestamp was None and the older timestamp was Some(...), which was clearly wrong.

**Comment by agrover** [comment]
Please keep the explicit listing of enumeration options

**Comment by trgill** [comment]
:+1: 
Ok.  It is intentional that equal and greater return the same thing?

**Comment by mulkieran** [comment]
It's a don't care in the extremely unlikely situation that the timestamps are equal. 1 is as good as 0.

The other option is to view two equal, non-None, timestamps as a sign that something is wrong, and return an error, but that is probably overkill.

**Comment by trgill** [comment]
Ok.

**Pull request merged**
