### PR TITLE
Package the thinpool device and extra segments together

### PR DESCRIPTION
**Pull request by mulkieran**
For better encapsulation.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by agrover** [comment]
great work 👍

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
The only difference from previous unrebased version is that no ```check()``` method is added to ThinPool implementation, i.e., the whole body of ```StratPool::check()``` is left in StratPool.

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by agrover** [comment]
👍 👍 👍 merging!

**Pull request merged**
