### PR TITLE
Implement FreeSpaceState with throttling, and a rudimentary PoolState

### PR DESCRIPTION
**Pull request by agrover**
Implement write throttling, and then use it when a pool reaches a certain percent full vs total pool capacity using a FreeSpaceState state machine. Use DM lowater event to get notified for FreeSpaceState transitions as well as its existing use to extend the data device.

Add a rudimentary PoolState enum, to handle error conditions.

### CODE REVIEW

**Comment by mulkieran** [comment]
Assuming that we concede that low water value shouldn't be set by pool but rather be managed by thinpool then it ought to be possible to move "Unpub DATA_LOWATER" and "Change ThinPool::setup()" commits to separate PR.

**Comment by agrover** [comment]
Opened #1085 with those commits. Parts of this PR needs them, so if the other one goes in quickly I'll rebase at that point.

**Comment by mulkieran** [comment]
There is some log output in Jenkins tests that seem to have resulted from this PR and maybe shouldn't be visible.

**Comment by mulkieran** [comment]
Please see https://github.com/stratis-storage/stratisd/pull/1116. I believe that the very last commit constitutes a bug fix. But, at this point, I'm not sure that ```data_excess``` is even a necessary field. Shouldn't the ```usage.total``` value obtained from the DM call be identical to the size of the thin pool device, which we can get through devicemapper-rs fairly cheaply? If so, we can look it up when we need it and not bother to store this value . If the low water value actually changes, we could store that instead, and if it doesn't...we don't have to store anything.

**Comment by mulkieran** [comment]
I've been taking a more serious look at the low water changes and my recommendation would be to drop the low water adjustments entirely and make this PR only about the throttling. It's not clear what effect the low water adjustments will have and they are definitely risky. I'll write up a few reasons why I think this in a bit, but these will take a little work to be clear (including actually taking notes on pieces of paper), so I don't have them in a presentable form right now.

**Comment by agrover** [comment]
The throttling depends on there being pool space states. Pool space states are only correct if we use low-water to detect when we should transition.

I also ended up drawing stuff out on a whiteboard. One key thing is that using the lowater event for extending the data dev is logically independent from Stratis tracking FreeSpaceState as a function of percentage-full. We're making the one event do double duty, which is unpleasant (but needed) -- calculating which of the two events would be hit first and setting the one threshold to trigger on that.

**Comment by agrover** [comment]
1. Yeah, I had pool init calling check() in an earlier version. I took it out because I couldn't think of a case where check() on a new pool would fail if all the preceding setup had been successful. Can you? I'll play around with putting it back.
1. opened #1126.

**Comment by mulkieran** [comment]
I ```think``` that if a pool was in a bad state when stratisd quit, then, if nothing much has happened, it ought to still be in a bad state when it is setup again.

**Comment by agrover** [comment]
True!

**Comment by agrover** [comment]
* Pull in @mulkieran 's tree
* Change ThinPool setup and new() to call check()
* Refactor extend_thin_sub_device, see commitlog for details.

**Comment by mulkieran** [comment]
Ok. Please see #1116 (two commits). With those two changes I think the PR is ready for its final version.

**Comment by mulkieran** [comment]
Whoops. I noticed that the stratisd Jenkins tests were failing. I think they are not so much failing as telling us something interesting. I think they are occasioned by running check() at setup() and new(). But that probably means that check() should be run then, because evidently it feels it needs to do something.

**Comment by mulkieran** [comment]
Ok. I added another commit to #1116 that may cause all to succeed.

**Comment by mulkieran** [comment]
That commit only causes the first previously failing test to succeed, but the others continue to fail. ```test_meta_expand``` seems to be failing because the meta device is not being expanded. This is very wierd, as, with these additions, it should be expanded when the thin pool is created. So, investigating.

**Comment by mulkieran** [comment]
Assuming test pass on #1116, and those changes were incorporated into this PR, I would feel that it was time to close this PR and open a final one.

**Comment by mulkieran** [comment]
Soon, it will make sense to try to factor some methods out of thinpool.rs before it becomes overwhelming.

```
> find . -name '*.rs' -exec wc -l {} \; | sort -n
5 ./src/stratis/stratis.rs
7 ./src/engine/sim_engine/mod.rs
11 ./src/engine/strat_engine/tests/mod.rs
11 ./src/engine/strat_engine/thinpool/mod.rs
12 ./src/stratis/util.rs
13 ./src/stratis/mod.rs
15 ./src/dbus_api/mod.rs
15 ./src/engine/strat_engine/tests/logger.rs
22 ./src/engine/strat_engine/backstore/mod.rs
22 ./src/engine/strat_engine/mod.rs
29 ./src/engine/strat_engine/cleanup.rs
32 ./src/engine/strat_engine/backstore/cleanup.rs
35 ./src/engine/mod.rs
36 ./src/engine/strat_engine/thinpool/thinids.rs
44 ./scripts/uml_graphs.rs
44 ./src/dbus_api/macros.rs
44 ./src/lib.rs
51 ./src/engine/strat_engine/dm.rs
62 ./src/engine/sim_engine/filesystem.rs
76 ./src/engine/strat_engine/device.rs
77 ./src/engine/sim_engine/randomization.rs
78 ./src/engine/strat_engine/serde_structs.rs
84 ./src/engine/macros.rs
93 ./src/engine/sim_engine/blockdev.rs
95 ./src/engine/types.rs
97 ./src/engine/strat_engine/backstore/util.rs
101 ./src/dbus_api/util.rs
111 ./src/engine/strat_engine/tests/util.rs
121 ./src/engine/strat_engine/tests/loopbacked.rs
132 ./src/engine/devlinks.rs
149 ./src/dbus_api/types.rs
149 ./src/stratis/errors.rs
156 ./src/engine/strat_engine/throttle.rs
166 ./src/engine/strat_engine/cmd.rs
185 ./src/engine/strat_engine/dmnames.rs
200 ./src/engine/strat_engine/backstore/device.rs
201 ./src/engine/strat_engine/backstore/blockdev.rs
230 ./src/stratis/buff_log.rs
231 ./src/dbus_api/filesystem.rs
243 ./src/engine/strat_engine/backstore/data_tier.rs
250 ./src/engine/strat_engine/tests/real.rs
252 ./src/engine/strat_engine/thinpool/mdv.rs
254 ./src/engine/strat_engine/backstore/cache_tier.rs
257 ./src/engine/engine.rs
265 ./src/dbus_api/blockdev.rs
284 ./src/dbus_api/api.rs
314 ./src/engine/strat_engine/backstore/setup.rs
325 ./src/engine/sim_engine/engine.rs
332 ./src/engine/strat_engine/thinpool/filesystem.rs
414 ./src/engine/strat_engine/engine.rs
450 ./src/dbus_api/pool.rs
458 ./src/bin/stratisd.rs
477 ./src/engine/strat_engine/backstore/range_alloc.rs
498 ./src/engine/sim_engine/pool.rs
538 ./src/engine/structures.rs
662 ./src/engine/strat_engine/pool.rs
769 ./src/engine/strat_engine/backstore/blockdevmgr.rs
842 ./src/engine/strat_engine/backstore/backstore.rs
1307 ./src/engine/strat_engine/backstore/metadata.rs
1832 ./src/engine/strat_engine/thinpool/thinpool.rs
```

When this PR has been committed I will file an issue about that.

**Comment by agrover** [comment]
closed in favor of #1133

**Pull request closed without merging**
