### PR TITLE
Move BDA::wipe

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #1584.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Do we know why the CI failed? I can't access it.

**Comment by mulkieran** [comment]
This is just a rebased version of #1616.

@GuillaumeGomez, the formatting bug was never fixed, so we just decided to update to the new Rust toolchain version and accept the new formatting.  did a rebase to get the formatting changes out. Otherwise, this should be identical to #1616. The test failure is due to a problem w/ our CI and we're just ignoring it for now.

**Comment by GuillaumeGomez** [comment]
I see, so there is basically nothing else to be done in here. I approved the PR. :)

**Comment by mulkieran** [comment]
> I see, so there is basically nothing else to be done in here. I approved the PR. :)

Thanks!

**Comment by mulkieran** [comment]
rebased.

**Pull request merged**
