### PR TITLE
Use udev to identify devices

### PR DESCRIPTION
**Pull request by mulkieran**
Supercedes #1043 .

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
I am moving this back into review because I have been told that somebody might be ready to review this now.

**Comment by mulkieran** [comment]
I am temporarily putting into review prelim, mostly because the last commit should be merged into a previous commit, but hasn't been yet.

**Comment by agrover** [comment]
I'm inclined to wait and tackle this PR after 1.0.

**Comment by mulkieran** [comment]
closed in favor of #1132.

**Pull request closed without merging**
