### PR TITLE
Remove config file requiring stratis dracut module to avoid initramfs generation failure

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Review by mulkieran — APPROVED** [review]

**Comment by refi64** [comment]
I'm probably missing something, but...how does stratisd-min get into the initramfs without this? At minimum, this change seems to have broken my boot on Fedora Silverblue; cryptsetup can never be set up because it's waiting for the Stratis block devices to appear, but they never come up since...well, stratisd-min missing from the initramfs.

**Comment by mulkieran** [comment]
@refi64 I'm sorry this decision is causing you an inconvenience. Please see Stratis 3.0.0 release notes[1] for an explanation of the decision. Working with dracut is always tricky; the downside of having that file but missing some other stratisd files is that the initramfs is not properly remade and your system will fail to boot, which seemed to us to be harder to recover from than the problem you are experiencing. We are giving the user more responsibility for configuring their initramfs; this seems like that the best we can do w/ dracut working the way it does.

[1] https://stratis-storage.github.io/stratis-release-notes-3-0-0/

**Comment by jbaublitz** [comment]
@refi64 If you run dracut with the `--verbose` option, it will tell you which requirement is not being met for Stratis not being included in the dracut initramfs. Does that help? If not, please file another bug and I'll take a look and guide you through it!

**Comment by refi64** [comment]
So to be clear, I don't necessarily *mind* the change, but [it also made its way into the 2.4.3 bugfix release](#2838), so I had what looked like a very plain system upgrade that ended up breaking the boot process.

I ran `dracut --verbose`, but it doesn't seem to mention Stratis at all without that config file in place (note that I had to mount a tmpfs onto /boot first, because I use Fedora Silverblue which has rpm-ostree run dracut, so I didn't want to accidentally mess with my main initramfs):

```
dracut: Executing: /usr/bin/dracut --verbose
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'dmraid' will not be installed, because command 'dmraid' could not be found!
dracut: *** Including module: bash ***
dracut: *** Including module: systemd ***
dracut: *** Including module: systemd-initrd ***
dracut: *** Including module: nss-softokn ***
dracut: *** Including module: i18n ***
dracut: *** Including module: drm ***
dracut: *** Including module: plymouth ***
dracut: *** Including module: crypt ***
dracut: *** Including module: dm ***
dracut: Skipping udev rule: 64-device-mapper.rules
dracut: Skipping udev rule: 60-persistent-storage-dm.rules
dracut: Skipping udev rule: 55-dm.rules
dracut: *** Including module: kernel-modules ***
dracut: *** Including module: kernel-modules-extra ***
dracut: *** Including module: resume ***
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: terminfo ***
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: Skipping udev rule: 70-persistent-net.rules
dracut: *** Including module: dracut-systemd ***
dracut: *** Including module: usrmount ***
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including module: memstrack ***
dracut: *** Including module: shutdown ***
dracut: *** Including modules done ***
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done ***
dracut: *** Hardlinking files ***
dracut: Mode:           real
dracut: Files:          1968
dracut: Linked:         98 files
dracut: Compared:       0 xattrs
dracut: Compared:       745 files
dracut: Saved:          5.44 MiB
dracut: Duration:       0.021851 seconds
dracut: *** Hardlinking files done ***
dracut: *** Generating early-microcode cpio image ***
dracut: *** Constructing GenuineIntel.bin ***
dracut: *** Store current command line parameters ***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Creating image file '/boot/initramfs-5.15.11-200.fc35.x86_64.img' ***
dracut: *** Creating initramfs image file '/boot/initramfs-5.15.11-200.fc35.x86_64.img' done ***
```

**Pull request merged**
