### PR TITLE
Updates for devicemapper v0.10

### PR DESCRIPTION
**Pull request by mulkieran**
An update for the new version.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
updated for newest version of devicemapper branch.

**Comment by mulkieran** [comment]
Updated to point at master.

**Comment by mulkieran** [comment]
@agrover @trgill review? We might be close to a new devicemapper version, so I'm putting this up for preliminary review.

**Comment by agrover** [comment]
The substance of this looks good to me. 👍

**Pull request merged**
