### PR TITLE
Improve BlockDevMgr::save_state()

### PR DESCRIPTION
**Pull request by mulkieran**
Get rid of the unwrap(). Consider the result a success if the metadata is
written somewhere. Obviously, for large pools, it would be desirable to
write to more than one blockdev, but if at least one was written to, it
should be possible to find the most up-to-date data next time it is needed,
or on setup.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
@agrover @trgill review?

**Comment by agrover** [comment]
A definite improvement. 👍

**Comment by mulkieran** [comment]
rebased.

**Comment by mulkieran** [comment]
This will start to block #424 pretty soon.

**Comment by mulkieran** [comment]
@trgill review?

**Pull request merged**
