### PR TITLE
github actions: Update pylint for Fedora 33

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related https://github.com/stratis-storage/project/issues/263

### CODE REVIEW

**Comment by mulkieran** [comment]
GitHub Actions may still be catching up...

**Comment by mulkieran** [comment]
@bgurney-rh They must have cancelled GitHub Actions start for this one. Might as well proceed and probably next push will kick off the GitHub Actions fine.

**Comment by bgurney-rh** [comment]
I ran an "amend" of the last commit to update its timestamp; that should hopefully trigger another run.

**Comment by bgurney-rh** [comment]
Interesting failure from the python 3.6.8, pylint 2.6.0... "make lint" run:
```
stratis_id/stratis_id.py:25: [E0401(import-error), ] Unable to import '_crc32'
```

**Comment by mulkieran** [comment]
> Interesting failure from the python 3.6.8, pylint 2.6.0... "make lint" run:
> 
> ```
> stratis_id/stratis_id.py:25: [E0401(import-error), ] Unable to import '_crc32'
> ```

Try setting PYTHONPATH before the make lint command in ```main.yml```. One possibly good value for PYTHONPATH is ```.```. If that doesn't work, we might consider dropping that ```stratis_id``` subdirectory. I'm not sure that anyone has ever used that script.

**Comment by mulkieran** [comment]
> > Interesting failure from the python 3.6.8, pylint 2.6.0... "make lint" run:
> > ```
> > stratis_id/stratis_id.py:25: [E0401(import-error), ] Unable to import '_crc32'
> > ```
> 
> Try setting PYTHONPATH before the make lint command in `main.yml`. One possibly good value for PYTHONPATH is `.`. If that doesn't work, we might consider dropping that `stratis_id` subdirectory. I'm not sure that anyone has ever used that script.

That probably won't work. Try applying the commit in https://github.com/stratis-storage/stratisd/pull/2453, and if that doesn't work I will consider removing the failing files.

**Comment by mulkieran** [comment]
@bgurney-rh Try applying the commit here: https://github.com/stratis-storage/stratisd/pull/2454 first. That really might work.

**Comment by mulkieran** [comment]
This looks ready. I'll push it to April. You might want to try picking off any individual commits that can be merged now. The last commit definitely qualifies, but maybe nothing else.

**Comment by bgurney-rh** [comment]
OK.  I want to remove the commit that has a matching revert, and I need to rebase on develop-2.3.0 anyway, so I created #2462 for the unused variable removal.  After that's merged, I can create a v2 of this PR, and get it down to 6 commits (or perhaps less, if I can squash similar commits together).

**Pull request closed without merging**
