### PR TITLE
Deny cargo clippy lints

### PR DESCRIPTION
**Pull request by bgurney-rh**
Supersedes: #2411 
Closes: #2408

### CODE REVIEW

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
@jbaublitz Just checking if you're comfortable w/ the license value. Of course, this is the one package that we don't push to crates.io yet, but if we did...

**Comment by bgurney-rh** [comment]
I can potentially use `Apache-2.0 OR MPL-2.0`.

**Review by drckeefe — APPROVED** [review]

**Comment by mulkieran** [comment]
We found out that we can refer to a file using some metadata field.

**Comment by mulkieran** [comment]
@bgurney-rh Can you follow this up using the suggested idea about the license file?

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks good. Please close this and open a final PR.

**Pull request closed without merging**
