### PR TITLE
Fully qualify non-prelude macro data types

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: #1748

### CODE REVIEW

**Comment by bgurney-rh** [comment]
I labeled this "do not merge", because I saw a failure in the stratisd test on my test machine:
```
---- engine::strat_engine::engine::test::real_test_pool_rename stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 123, kind: Other, message: "No medium found" })', src/libcore/result.rs:1084:5
```

```
---- engine::strat_engine::engine::test::real_test_setup stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 123, kind: Other, message: "No medium found" })', src/libcore/result.rs:1084:5
```

**Comment by jbaublitz** [comment]
@bgurney-rh Just a note that this is highly unlikely to have caused that error. I'll wait for CI to complete but path-only changes in a macro will never cause a behavior change as long as nothing else is modified. The errors would only be at compile time.

**Comment by mulkieran** [comment]
> @bgurney-rh Just a note that this is highly unlikely to have caused that error. I'll wait for CI to complete but path-only changes in a macro will never cause a behavior change as long as nothing else is modified. The errors would only be at compile time.

Yup. I agree with @jbaublitz. These changes can't have caused that error.

**Comment by bgurney-rh** [comment]
Well, the stratisd test in CI passed.  It's probably time to reset my test machine that produced the failure above.

**Comment by bgurney-rh** [comment]
> Looks like you got all the types in `dbus_api/macros.rs` but not in `engine/macros.rs`

Should be resolved in the last push; I missed a couple of ErrorEnum entries.

**Comment by bgurney-rh** [comment]
I also fully qualified RenameAction in macro.rs; hopefully that's everything.

**Comment by bgurney-rh** [comment]
I also added devicemapper::SECTOR_SIZE in src/engine/strat_engine/backstore/metadata/bda.rs, in the "bytes" macro.

**Comment by bgurney-rh** [comment]
Rebased.

**Comment by bgurney-rh** [comment]
After re-reading through engine/macros.rs and dbus_api/macros.rs, it looks like I fully qualified everything that could be.

**Comment by bgurney-rh** [comment]
OK; new PR should be posting in a minute or so.

**Pull request closed without merging**
