### PR TITLE
Remove force option from dbus API

### PR DESCRIPTION
**Pull request by tasleson**
Remove dbus force option and remove it from the internal function calls as well.

### CODE REVIEW

**Comment by tasleson** [comment]
Fixes https://github.com/stratis-storage/stratisd/issues/613

**Comment by mulkieran** [comment]
I'm happy with the changes to the stratisd src. But ```_data.py``` in tests will have to be updated to make stratisd tests pass. cli-with-stratisd tests will fail until CLI update goes in, so that failure should be ignored.

**Comment by tasleson** [comment]
>  But _data.py in tests will have to be updated to make stratisd tests pass.

Thanks for that, should have grep'd around more :smile:

**Comment by tasleson** [comment]
Pulling this back into 'in progress', missed a bunch of the dbus tests, ugh.

**Comment by tasleson** [comment]
The `make fmt-travis` works clean on my local system, :disappointed:

**Comment by tasleson** [comment]
I'm at a loss to why the resume on the cache device fails with this change when the test function `test_add_cache_devs` is functionally equivalent, any ideas @agrover @mulkieran @trgill ?

``` rust
...
if cache_change {
    let table = map_to_dm(&cache_tier.cache_segments);
     cache_device.set_cache_table(get_dm(), table)?;
     cache_device.resume(get_dm())?;
 }
...
```
```
---- engine::strat_engine::backstore::backstore::tests::real_test_add_cache_devs stdout ----
	thread 'engine::strat_engine::backstore::backstore::tests::real_test_add_cache_devs' panicked at 'called `Result::unwrap()` on an `Err` value: DM(Core(Error(IoctlError(DeviceInfo { hdr: Struct_dm_ioctl { version: [4, 30, 0], data_size: 16384, data_start: 312, target_count: 0, open_count: 0, flags: 0, event_nr: 0, dev: Device { major: 0, minor: 0 }, name: "stratis-1-private-dbe29c4613894a7f87422c5e1e0853cc-physical-cache", uuid: "" } }, Sys(ENODATA)), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x558150618504 - backtrace::backtrace::libunwind::trace::h984c700674cf85f6
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h6b85dbb32533085f
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/backtrace/mod.rs:42
   1:     0x55815061617c - backtrace::capture::Backtrace::new_unresolved::h3b3913fb6ca9d10b
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.3/src/capture.rs:88
   2:     0x558150612255 - error_chain::backtrace::imp::InternalBacktrace::new::h76b0f1356281dfa1
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.0/src/backtrace.rs:56
   3:     0x55815061369f - <error_chain::State as core::default::Default>::default::h33b3974c921d6923
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.12.0/src/lib.rs:666
   4:     0x5581505bad55 - devicemapper::errors::Error::from_kind::h64396df14fd04893
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.0/<impl_error_chain_processed macros>:53
   5:     0x5581505bae67 - <devicemapper::errors::Error as core::convert::From<devicemapper::errors::ErrorKind>>::from::h1859c06ab3d35ac6
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.0/src/errors.rs:12
   6:     0x5581505b8b77 - <T as core::convert::Into<U>>::into::h690f416c81ddef2c
                        at /checkout/src/libcore/convert.rs:396
   7:     0x5581505ccd71 - devicemapper::dm::DM::do_ioctl::h0cc1ab14ce9ca441
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.0/src/dm.rs:143
   8:     0x5581505ceafc - devicemapper::dm::DM::device_suspend::ha16b95faca44c898
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.0/src/dm.rs:367
   9:     0x5581501eca4e - devicemapper::shared::DmDevice::resume::h79a148e05f885cb5
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-0.26.0/src/shared.rs:82
  10:     0x558150050668 - libstratis::engine::strat_engine::backstore::backstore::Backstore::add_cachedevs::h9ac9a8bbe420dad5
                        at src/engine/strat_engine/backstore/backstore.rs:196
  11:     0x5581500516da - libstratis::engine::strat_engine::backstore::backstore::Backstore::add_blockdevs::h986a3aecf26b264f
                        at src/engine/strat_engine/backstore/backstore.rs:257
  12:     0x55815000875a - libstratis::engine::strat_engine::backstore::backstore::tests::test_add_cache_devs::hd2f3e523c6c9f58e
                        at src/engine/strat_engine/backstore/backstore.rs:662
  13:     0x55814ff7f190 - core::ops::function::Fn::call::h991f3d54df373256
                        at /checkout/src/libcore/ops/function.rs:73
  14:     0x55815020d8bf - libstratis::engine::strat_engine::tests::real::test_with_spec::{{closure}}::h9187ebc6a54f8ebe
                        at src/engine/strat_engine/tests/real.rs:240
  15:     0x55815000f949 - std::panicking::try::do_call::hc6dc2044c8dec756
                        at /checkout/src/libstd/panicking.rs:306
  16:     0x558150657e4e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  17:     0x55815000ca00 - std::panicking::try::h6ffe41f6b39322da
                        at /checkout/src/libstd/panicking.rs:285
  18:     0x5581500bc3ec - std::panic::catch_unwind::hb123871256e7d642
                        at /checkout/src/libstd/panic.rs:361
  19:     0x5581501fcbe7 - libstratis::engine::strat_engine::tests::real::test_with_spec::h9cab0dc3bcbd244b
                        at src/engine/strat_engine/tests/real.rs:240
  20:     0x558150009120 - libstratis::engine::strat_engine::backstore::backstore::tests::real_test_add_cache_devs::h6a7628cf85cb7453
                        at src/engine/strat_engine/backstore/backstore.rs:697
  21:     0x55814ff74670 - libstratis::__test::TESTS::{{closure}}::h989c99a5515cf248
                        at src/engine/strat_engine/backstore/backstore.rs:696
  22:     0x55814ff80410 - core::ops::function::FnOnce::call_once::h6d3c50ee20d4f479
                        at /checkout/src/libcore/ops/function.rs:223
  23:     0x55815023c001 - test::run_test::{{closure}}::hb5d72fe898bc8358
                        at libtest/lib.rs:1453
                         - core::ops::function::FnOnce::call_once::hfb87b8f8cd3db1ed
                        at /checkout/src/libcore/ops/function.rs:223
                         - <F as alloc::boxed::FnBox<A>>::call_box::h72ac1ed3a3cc6cc3
                        at /checkout/src/liballoc/boxed.rs:784
  24:     0x558150657e4e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  25:     0x55815024ebca - std::panicking::try::h4d9a815971e21d46
                        at /checkout/src/libstd/panicking.rs:285
                         - std::panic::catch_unwind::h07ff5ae0e58b0551
                        at /checkout/src/libstd/panic.rs:361
                         - test::run_test::run_test_inner::{{closure}}::hafffe6080a37bca9
                        at libtest/lib.rs:1408
                         - std::sys_common::backtrace::__rust_begin_short_backtrace::h7cdd4303e91ee57b
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  26:     0x55815024abb2 - std::thread::Builder::spawn::{{closure}}::{{closure}}::h52bea869b19b2e6b
                        at /checkout/src/libstd/thread/mod.rs:406
                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8401fb7dc246c94e
                        at /checkout/src/libstd/panic.rs:296
                         - std::panicking::try::do_call::h768f54c243670646
                        at /checkout/src/libstd/panicking.rs:306
  27:     0x558150657e4e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  28:     0x55815025fa33 - std::panicking::try::h091eea4a2adda474
                        at /checkout/src/libstd/panicking.rs:285
                         - std::panic::catch_unwind::h64fe2e8d887d644a
                        at /checkout/src/libstd/panic.rs:361
                         - std::thread::Builder::spawn::{{closure}}::h66dc98cab93dd457
                        at /checkout/src/libstd/thread/mod.rs:405
                         - <F as alloc::boxed::FnBox<A>>::call_box::h95f1bc89de8ed4dd
                        at /checkout/src/liballoc/boxed.rs:784
  29:     0x55815064cf37 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h3a46ab40d44ff8db
                        at /checkout/src/liballoc/boxed.rs:794
                         - std::sys_common::thread::start_thread::heca3dbba8ff4f46a
                        at libstd/sys_common/thread.rs:24
  30:     0x558150637e58 - std::sys::unix::thread::Thread::new::thread_start::ha1ecaaa6d3efa77d
                        at libstd/sys/unix/thread.rs:90
  31:     0x7fd3ebbb5593 - start_thread
  32:     0x7fd3eb6d0e6e - clone
  33:                0x0 - <unknown>) } })))', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Code change for the function `test_add_cache_devs`
``` diff
@@ -625,7 +621,7 @@ mod tests {
 
         let pool_uuid = Uuid::new_v4();
         let mut backstore =
-            Backstore::initialize(pool_uuid, initdatapaths, MIN_MDA_SECTORS, false).unwrap();
+            Backstore::initialize(pool_uuid, initdatapaths, MIN_MDA_SECTORS).unwrap();
 
         invariant(&backstore);
 
@@ -633,7 +629,7 @@ mod tests {
         backstore.alloc(pool_uuid, &[Sectors(1)]).unwrap();
 
         let cache_uuids = backstore
-            .add_blockdevs(pool_uuid, initcachepaths, BlockDevTier::Cache, false)
+            .add_blockdevs(pool_uuid, initcachepaths, BlockDevTier::Cache)
             .unwrap();
 
         invariant(&backstore);
@@ -658,13 +654,13 @@ mod tests {
         }
 
         let data_uuids = backstore
-            .add_blockdevs(pool_uuid, datadevpaths, BlockDevTier::Data, false)
+            .add_blockdevs(pool_uuid, datadevpaths, BlockDevTier::Data)
             .unwrap();
         invariant(&backstore);
         assert_eq!(data_uuids.len(), datadevpaths.len());
 
         let cache_uuids = backstore
-            .add_blockdevs(pool_uuid, cachedevpaths, BlockDevTier::Cache, false)
+            .add_blockdevs(pool_uuid, cachedevpaths, BlockDevTier::Cache)
             .unwrap();
```

**Comment by agrover** [comment]
I suspect this is a dm-cache regression. This passes with 4.17.19-200.fc28.x86_64 but this branch (and v0.9.0 and master) fail for me on 4.18.8-200.fc28.x86_64:

```
[   95.754178] device-mapper: cache metadata: dm_array_cursor_next for hint failed
[   95.754181] device-mapper: cache: 253:3: could not load cache mappings
[   95.754183] device-mapper: cache: 253:3: metadata operation 'dm_cache_load_mappings' failed: error = -61
[   95.754184] device-mapper: cache: 253:3: aborting current metadata transaction
[   95.758512] device-mapper: cache: 253:3: switching cache to read-only mode
[   95.758513] device-mapper: table: 253:3: cache: preresume failed, error = -61
```
I'll open an issue, but for now I recommend we stay on kernel.4.17 on our Jenkins nodes.

**Comment by agrover** [comment]
@trgill says he's going to move Jenkins nodes back to unaffected kernel versions, so once he does I think this PR should pass CI.

**Comment by agrover** [comment]
Manually merged.

**Pull request merged**
